// Breaks one rule at a time and requires the suite to notice. A mutant counts as
// caught only when a check prints FAIL; a crash with no FAIL line is reported apart.
import { readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const M = [
  // rules
  ['src/sim.js', "if (s.powers.boomerang) { p.dir = k;", "if (s.powers.boomerang) {", 'sim'],
  ['src/sim.js', "if (r === 'moved') { if (s.clock === 'tile') worldStep(s, d); return true; }", "if (r === 'moved') return true;", 'sim'],
  ['src/sim.js', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (false) { kill(s, o, how); return true; }", 'sim'],
  ['src/sim.js', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (ENEMY.includes(o.kind)) { kill(s, o, how); return true; }", 'sim'],
  ['src/sim.js', "} else if (e.kind === 'box' && (b = pushTo(s, nx, ny, t.d, false))) land(s, e, b);", "} else if (false) {}", 'sim'],
  ['src/sim.js', "if (e.kind === 'heavy' && ENEMY.includes(o.kind)) kill(s, o, 'squash');", "if (false) kill(s, o, 'squash');", 'sim'],
  ['src/sim.js', "if (e.kind === 'heavy' && ENEMY.includes(o.kind)) kill(s, o, 'squash');", "if (e.kind === 'heavy' && o.kind === 'enemy') kill(s, o, 'squash');", 'sim'],
  ['src/sim.js', "else { e.x = t.x; e.y = t.y; die(s); return; }", "else { e.dir = -e.dir; return; }", 'sim'],
  ['src/sim.js', "pressed[col] = (pressed[col] ?? true) && down;", "pressed[col] = (pressed[col] ?? false) || down;", 'sim'],
  ['src/sim.js', "const playerAt = (s, x, y) => !s.player.hidden && s.player.x === x", "const playerAt = (s, x, y) => s.player.x === x", 'sim'],
  ['src/sim.js', "if (++p.hideTicks < HIDE_TICKS || s.entities.some(e => !e.dead && e.rush)) return;", "if (++p.hideTicks < HIDE_TICKS) return;", 'sim'],
  ['src/sim.js', "crushes(s, e)) || solidCell(s, p.x, p.y)) {", "crushes(s, e))) {", 'sim'],
  ['src/sim.js', "if (s.entities.some(e => !e.dead && e.x === p.x && e.y === p.y && crushes(s, e)) || solidCell", "if (solidCell", 'sim'],
  ['src/sim.js', "if (!DIRS[k] || p.hidden) return;", "if (!DIRS[k]) return;", 'sim'],
  ['src/sim.js', "if (p.dir || p.hidden) return;", "if (p.dir) return;", 'sim'],
  ['src/sim.js', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "if (cellAt(s, x, y).startsWith('sensor:') && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", 'sim'],
  ['src/sim.js', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "", 'sim'],
  ['src/sim.js', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "", 'sim'],
  ['src/sim.js', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "else if (c.startsWith('sensor:')) { col = c.slice(7); down = true; }", 'sim'],
  ['src/sim.js', "if (c.startsWith('sensor:')) return COLOURS.includes(c.slice(7));", "", 'sim'],
  ['src/sim.js', "if (s.tick % RT_PERIOD === RT_PERIOD - 1)", "if (false)", 'sim'],
  ['src/sim.js', "    s.checkpoint = { x: nx, y: ny };\n", "", 'sim'],
  ['src/sim.js', "for (const c of l.cells) if (!isCell(c)) throw new Error('Unknown tile: ' + c);", "", 'sim'],
  ['src/sim.js', "if (moved > 0 && s.clock === 'slide')", "if (s.clock === 'slide')", 'sim'],
  ['src/sim.js', "return !s.open[c.slice(5)];", "return false;", 'sim'],
  ['src/sim.js', "  if (playerAt(s, t.x, t.y)) die(s);\n  else if (ridden", "  if (ridden", 'sim'],
  ['src/sim.js', "if (o.kind === 'box' && (b = pushTo(s, t.x, t.y, t.d, false))) land(s, o, b);", "if (false) {}", 'sim'],
  ['src/sim.js', "if (diving) { e.slide = t.d;", "if (false) { e.slide = t.d;", 'sim'],
  ['src/sim.js', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (false) kill(s, e, 'dive');", 'sim'],
  ['src/sim.js', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (ENEMY.includes(e.kind) && diving) kill(s, e, 'dive');", 'sim'],
  ['src/sim.js', "dirs: CLOCKWISE.filter(d => e.turret.dirs.includes(d))", "dirs: e.turret.dirs", 'sim'],
  ['src/sim.js', "|| new Set(t.dirs).size !== t.dirs.length)", ")", 'sim'],
  ['src/sim.js', "else if (e.mode === 'follow') moveMover(s, e, d);", "else if (e.mode === 'follow') moveMover(s, e);", 'sim'],
  ['src/sim.js', "if (moved > 0 && s.clock === 'slide') worldStep(s, d);", "if (moved > 0 && s.clock === 'slide') worldStep(s, 'up');", 'sim'],
  ['src/sim.js', "if (!turned) moveMover(s, e, null, true);", "", 'sim'],
  ['src/sim.js', "const blocked = () => { if (d) return;", "const blocked = () => {", 'sim'],
  ['src/sim.js', "if (tri && !openFaces(tri).includes(ENTRY_FACE[d])) return null;", "", 'sim'],
  ['src/sim.js', "  if (p.dir) p.dir = t.d;\n", "", 'sim'],
  ['src/sim.js', "e.x = t.x; e.y = t.y; e.slide = t.d;", "e.x = t.x; e.y = t.y;", 'sim'],
  ['src/sim.js', "if (e.x === x && e.y === y) e.rush = false;", "e.rush = false;", 'sim'],
  ['src/sim.js', "if (!e.dead && e.mode === 'input' && MOVES.includes(e.kind)) e.rush = true;", "", 'sim'],
  ['src/sim.js', "if (c.startsWith('tri:')) return CORNERS.includes(c.slice(4));", "if (c.startsWith('tri:')) return true;", 'sim'],
  ['src/sim.js', "return here && !openFaces(here).includes(EXIT_FACE[d]) ? turn(here, d) : d;", "return d;", 'sim'],
  ['src/sim.js', "const aimOf = t => t.dirs[t.aim % t.dirs.length];", "const aimOf = t => t.dirs[0];", 'sim'],
  ['src/sim.js', "  turnTurrets(s, 'input');\n  for (const e of s.entities) if (!e.dead && e.turret && e.turret.mode === 'follow'", "  for (const e of s.entities) if (!e.dead && e.turret && e.turret.mode === 'follow'", 'sim'],
  ['src/sim.js', "    turnTurrets(s, 'realtime');\n", "", 'sim'],
  ['src/sim.js', "e.turret.mode === 'follow' && e.turret.dirs.includes(d)) e.turret.aim = e.turret.dirs.indexOf(d);", "e.turret.mode === 'follow') e.turret.aim = Math.max(0, e.turret.dirs.indexOf(d));", 'sim'],
  ['src/sim.js', "  computeBeams(s, true);\n", "", 'sim'],
  ['src/sim.js', "if (harm && hitYou) die(s);", "", 'sim'],
  ['src/sim.js', "if (r.stop && inb(s, ...r.stop) && cellAt(s, ...r.stop).startsWith('receiver:')) s.lit.add(r.stop[1] * s.w + r.stop[0]);", "", 'sim'],
  ['src/sim.js', "else if (c.startsWith('receiver:')) { col = c.slice(9); down = s.lit.has(i); }", "else if (c.startsWith('receiver:')) { col = c.slice(9); down = true; }", 'sim'],
  ['src/sim.js', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('spring:')) return true;", 'sim'],
  ['src/sim.js', "if (c.startsWith('receiver:')) return COLOURS.includes(c.slice(9));", "if (c.startsWith('receiver:')) return true;", 'sim'],
  ['src/main.js', "  if (ui.tool === 'look') { $('placeHint').textContent = describe(c.x, c.y); return; }\n", "", 'browser'],
  ['src/main.js', "  if (m === 'edit') { ui.tool = 'look'; ui.group = 'basic'; }\n", "", 'browser'],
  ['src/sim.js', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (to && !to.includes(d)) return null;", 'sim'],
  ['src/sim.js', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (from && !from.includes(d)) return null;", 'sim'],
  ['src/sim.js', "return ds.length > 0 && new Set(ds).size === ds.length && ds.every(d => CLOCKWISE.includes(d));", "return true;", 'sim'],
  ['src/main.js', "removePiece(); setCell('gate:' + CLOCKWISE.filter(d => ui.pass.includes(d)).join(','));", "removePiece(); setCell('gate:right');", 'browser'],
  ['src/main.js', "b.disabled = on && ui.pass.length === 1;", "b.disabled = false;", 'browser'],
  ['src/sim.js', "if (cellAt(s, nx, ny) === 'death') return { x: nx, y: ny, d, death: true };", "", 'sim'],
  ['src/sim.js', "  if (t.death) { die(s); return 'died'; }\n", "", 'sim'],
  ['src/sim.js', "  if (t.death) { kill(s, e, 'death'); return false; }\n", "", 'sim'],
  ['src/sim.js', "  if (t.death) { kill(s, e, 'death'); return; }\n  const o = entAt(s, t.x, t.y, e);\n  let b;", "  const o = entAt(s, t.x, t.y, e);\n  let b;", 'sim'],
  ['src/sim.js', "  if (t.death) { kill(s, e, 'death'); return; }\n  const o = entAt(s, t.x, t.y, e);\n  if (o) {\n    if (e.kind === 'heavy'", "  const o = entAt(s, t.x, t.y, e);\n  if (o) {\n    if (e.kind === 'heavy'", 'sim'],
  ['src/sim.js', "if (!t || t.death) { cd = facing", "if (!t) { cd = facing", 'sim'],
  ['src/sim.js', "  fireSprings(s);\n", "", 'sim'],
  ['src/sim.js', "if (playerAt(s, x, y) && p.dir !== d && stepTo(s, x, y, d, p.swimming)) {", "if (playerAt(s, x, y) && p.dir !== d) {", 'sim'],
  ['src/sim.js', "if (e && e.kind !== 'turret' && e.slide !== d && stepTo(s, x, y, d, wades(e))) {", "if (false) {", 'sim'],
  ['src/sim.js', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('receiver:')) return true;", 'sim'],
  ['src/main.js', "removePiece(); setCell(t === 'death' ? 'death' : 'spring:' + ui.face);", "removePiece(); setCell(t === 'death' ? 'death' : 'spring:up');", 'browser'],
  // page
  ['src/main.js', "if (host && (CARRIES_TURRET.includes(host.kind) || host.kind === 'turret')) {", "if (false) {", 'browser'],
  ['src/main.js', "b.disabled = on && ui.aim.length === 1;", "b.disabled = false;", 'browser'],
  ['src/main.js', "if (ui.mode === 'follow') $('axisOpt').hidden = true;", "", 'browser'],
  ['src/main.js', "painting = ev.button === 2 ? 'erase' : holds(c.x, c.y, ui.tool) && ui.tool !== 'start' ? 'remove' : 'place';", "painting = ev.button === 2 ? 'erase' : 'place';", 'browser'],
  ['src/main.js', "if (ui.tool === 'turret' && host && host.kind !== 'turret') { gone.piece = { ...host }; delete host.turret; }", "if (false) {}", 'browser'],
  ['src/main.js', "  if (how === 'remove' && !holds(x, y, ui.tool)) return;\n", "", 'browser'],
  ['src/main.js', "removePiece(); setCell('tri:' + ui.corner);", "removePiece(); setCell('tri:se');", 'browser'],
  ['src/main.js', "if (d !== swipe.last) pending.push(d);", "", 'phone'],
  ['src/main.js', "if (painting && c && ui.tool !== 'start') place(c.x, c.y, painting);", "if (painting && hover && ui.tool !== 'start') place(hover.x, hover.y, painting);", 'phone'],
  ['src/main.js', "$('hideBtn').onclick = () => pending.push('hide');", "", 'phone'],
  ['src/main.js', "const l = portrait() ? emptyLevel(12, 14) : emptyLevel(20, 12);", "const l = emptyLevel(20, 12);", 'phone'],
  ['src/main.js', "const zoom = Math.min(2.5, stage / (level.w * T), room / (level.h * T));", "const zoom = Math.max(1, Math.min(2.5, stage / (level.w * T), room / (level.h * T)));", 'phone'],
  ['src/main.js', "  for (const k of pending) keylog.push({ t: game.tick, k });\n", "", 'phone'],
  ['src/main.js', "played = JSON.parse(JSON.stringify(level)); keylog = [];", "played = level; keylog = [];", 'phone'],
  ['style.css', ".opt[hidden] { display: none; }", "", 'browser'],
  ['style.css', "grid-template-columns: 256px", "grid-template-columns: 200px", 'browser'],
  ['src/main.js', "a.download = 'room.wee';", "a.download = 'room.json';", 'browser'],
  ['src/main.js', "if (!ev.repeat) pending.push(k);", "", 'browser'],
  ['src/main.js', "if (t === 'erase') {\n    if (pi >= 0) removePiece(); else setCell('');", "if (t === 'erase') {", 'browser'],
  ['src/sim.js', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => true;", 'sim'],
  ['src/sim.js', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'heavy' || !s.powers.armored;", 'sim'],
  ['src/sim.js', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'strong' || !s.powers.armored;", 'sim'],
  ['src/sim.js', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['heavy', 'mover'];", 'sim'],
  ['src/sim.js', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['strong', 'heavy', 'mover', 'box', 'enemy'];", 'sim'],
  ['src/sim.js', "|| (youIn(d) && s.powers.armored))) continue;", ")) continue;", 'sim'],
  ['src/sim.js', "for (const e of inside(d)) kill(s, e, 'door');", "", 'sim'],
  ['src/sim.js', "if (youIn(d) && !s.player.hidden) squashed = true;", "", 'sim'],
  ['src/sim.js', "if (!crushes(s, e)) return 'blocked'; die(s); return 'died';", "die(s); return 'died';", 'sim'],
  ['src/sim.js', "      if (!crushes(s, e)) { blocked(); return; }\n      e.x = t.x;", "      e.x = t.x;", 'sim'],
  ['src/sim.js', "    else if (!crushes(s, e)) { blocked(); return; }\n", "", 'sim'],
  ['src/sim.js', "(!crushes(s, e) || (e.kind !== 'heavy'", "((e.kind !== 'heavy'", 'sim'],
  ['src/sim.js', "e.x === p.x && e.y === p.y && crushes(s, e))", "e.x === p.x && e.y === p.y)", 'sim'],
  ['src/render.js', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);", "drawPlayer(g, px, py, p.hidden, scale, 1, false, swim, p.sticky);", 'browser'],
  ['src/sim.js', "if (!wet && cellAt(s, nx, ny) === 'water') return null;", "", 'sim'],
  ['src/sim.js', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy'];", 'sim'],
  ['src/sim.js', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'mover'];", 'sim'],
  ['src/sim.js', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['heavy', 'mover'];", 'sim'],
  ['src/sim.js', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy', 'mover', 'enemy'];", 'sim'],
  ['src/sim.js', "const p = s.player, t = stepTo(s, p.x, p.y, d, p.swimming);", "const p = s.player, t = stepTo(s, p.x, p.y, d);", 'sim'],
  ['src/sim.js', "(b = pushTo(s, nx, ny, t.d, false))", "(b = pushTo(s, nx, ny, t.d))", 'sim'],
  ['src/sim.js', "const swim = s.powers.swim && !inWater(s, p.x, p.y);", "const swim = s.powers.swim;", 'sim'],
  ['src/sim.js', "if (!s.powers.cycle && !swim) return;", "", 'sim'],
  ['src/sim.js', "if (s.powers.cycle) { p.hidden = true;", "if (true) { p.hidden = true;", 'sim'],
  ['src/sim.js', "s.player.stroke = inWater(s, s.player.x, s.player.y) ? !s.player.stroke : false;", "s.player.stroke = false;", 'sim'],
  ['src/sim.js', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "", 'sim'],
  ['src/sim.js', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "for (const [dx, dy] of Object.values(DIRS)) if (inb(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", 'sim'],
  ['src/sim.js', "return pools.has(s.player.y * s.w + s.player.x) && !s.player.hidden;", "return pools.has(s.player.y * s.w + s.player.x);", 'sim'],
  ['src/sim.js', "for (const e of s.entities) if (!e.dead && pools.has(e.y * s.w + e.x)) laserHit(s, e, how);", "", 'sim'],
  ['src/sim.js', "  if (harm && shockHarms(s, s.shocked, 'turret')) hitYou = true;\n", "", 'sim'],
  ['src/sim.js', "  if (shockHarms(s, pools, 'laser')) die(s);\n", "", 'sim'],
  ['src/sim.js', "if (c === 'death' || c === 'water' || c === 'sticky') return true;", "if (c === 'death' || c === 'sticky') return true;", 'sim'],
  ['src/main.js', "} else if (t === 'water' || t === 'sticky') {\n    if (isStart) return;\n    setCell(t);", "} else if (false) {", 'browser'],
  ['src/main.js', "b.hidden = b.dataset.in !== ui.group;", "", 'phone'],
  ['src/main.js', "$('hideBtn').hidden = !tap.length; ", "", 'phone'],
  ['src/main.js', "$('hideBtn').textContent = tap.join(' / ');", "$('hideBtn').textContent = 'Hide / Swim';", 'phone'],
  ['src/main.js', "pending.push(`power:${p}:${box.checked ? 1 : 0}`); syncPanel(); };", "pending.push(`power:${p}:${box.checked ? 1 : 0}`); };", 'phone'],
  ['src/main.js', "if (m === 'edit') { ui.tool = 'look'; ui.group = 'basic'; }", "if (m === 'edit') { ui.tool = 'look'; }", 'browser'],
  ['style.css', "  #tools > h2:first-child { display: none; }\n", "", 'phone'],
  ['src/main.js', ": '')", ": 'Press Play to try this room.')", 'phone'],
  ['src/sim.js', "if (c === 'sticky' && !p.stuck && !p.sticky) { p.sticky = true;", "if (false) { p.sticky = true;", 'sim'],
  ['src/sim.js', "if (c === 'water') { p.sticky = false; unstick(s); }", "", 'sim'],
  ['src/sim.js', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || e.kind === 'heavy';", 'sim'],
  ['src/sim.js', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", 'sim'],
  ['src/sim.js', "  p.sticky = false;\n  p.stuck = { id: e.id,", "  p.stuck = { id: e.id,", 'sim'],
  ['src/sim.js', "ride: e.kind === 'mover' || !!e.slide,", "ride: e.kind === 'mover',", 'sim'],
  ['src/sim.js', "if (!b) { unstick(s); return 'blocked'; }", "if (!b) { return 'blocked'; }", 'sim'],
  ['src/sim.js', "} else if (e && p.sticky && STICKS(e)) { stick(s, e); return 'blocked'; }", "}", 'sim'],
  ['src/sim.js', "if (g && !ahead) drag(s, g, dx, dy);", "", 'sim'],
  ['src/sim.js', "if (g && !ahead) drag(s, g, dx, dy);", "if (g) drag(s, g, dx, dy);", 'sim'],
  ['src/sim.js', "if (t) land(s, g, t);", "", 'sim'],
  ['src/sim.js', "  if (p.stuck && p.stuck.ride) unstick(s);\n", "", 'sim'],
  ['src/sim.js', "if (ridden && !pushed && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src/sim.js', "if (!ridden) stick(s, e);", "", 'sim'],
  ['src/sim.js', "if (playerAt(s, t.x, t.y) && (ridden || p.sticky) && !ENEMY.includes(e.kind)) {", "if (false) {", 'sim'],
  ['src/sim.js', "else if (ridden && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src/sim.js', "if (e.kind === 'box') st.ride = false; else unstick(s);", "unstick(s);", 'sim'],
  ['src/sim.js', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", 'sim'],
  ['src/sim.js', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || p.hidden) { unstick(s); return; }", 'sim'],
  ['src/sim.js', "if (c === 'death' || c === 'water' || c === 'sticky') return true;", "if (c === 'death' || c === 'water') return true;", 'sim'],
  ['src/main.js', "  { id: 'sticky', label: 'Sticky puddle', group: 'tiles' },\n", "", 'browser'],
  ['style.css', "  .grid button[hidden] { display: flex; }\n  main {", "  main {", 'browser'],
  ['style.css', "  .tabs, #tools > h2:first-child { display: none; }\n", "", 'browser'],
  ['style.css', "  .ghead { display: block; }\n", "", 'browser'],
  ['src/sim.js', "  s.entities = freshPieces(s.origin);\n", "", 'sim'],
  ['src/sim.js', "  for (const e of s.entities) e.dead = true;\n", "", 'sim'],
  ['src/sim.js', "if (s.powers.boomerang) { letGo(s); p.dir = k;", "if (s.powers.boomerang) { p.dir = k;", 'sim'],
  ['src/sim.js', "{ if (land(s, e, b)) pushed = { id: e.id, d: b.d }; }", "land(s, e, b);", 'sim'],
  ['src/sim.js', "  p.pushing = pushed;\n", "", 'sim'],
  ['src/sim.js', "if (e && !e.slide) e.slide = pu.d;", "if (e && !e.slide) e.slide = OPPOSITE[pu.d];", 'sim'],
  ['src/main.js', "tool === 'receiver' || tool === 'sensor' || tool === 'gate') return", "tool === 'receiver' || tool === 'gate') return", 'browser'],
  ['src/render.js', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);\n  g.restore();", "g.restore();", 'browser'],
];

let caught = 0, crashed = 0;
for (const [file, from, to, test] of M) {
  if (process.env.ONLY && !from.includes(process.env.ONLY)) { caught++; continue; }
  const orig = readFileSync(file, 'utf8');
  if (!orig.includes(from)) { console.log(`STALE mutant in ${file}: ${from.slice(0, 50)}`); process.exitCode = 1; continue; }
  writeFileSync(file, orig.replace(from, to));
  try {
    const r = spawnSync('node', [`tests/${test}.${test === 'sim' ? 'test' : 'smoke'}.mjs`], { encoding: 'utf8' });
    const out = r.stdout + r.stderr;
    const fail = out.split('\n').find(l => l.startsWith('FAIL'));
    if (fail) { caught++; console.log(`caught  ${fail.slice(0, 90)}`); }
    else if (r.status !== 0) { crashed++; console.log(`CRASHED ${file}: ${from.slice(0, 50)}`); }
    else console.log(`SURVIVED ${file}: ${from.slice(0, 60)}`);
  } finally { writeFileSync(file, orig); }
}
console.log(`mutants: ${caught}/${M.length} caught${crashed ? `, ${crashed} crashed` : ''}`);
process.exit(caught === M.length ? 0 : 1);
