// Breaks one rule at a time and requires the suite to notice. A mutant counts as
// caught only when a check prints FAIL; a crash with no FAIL line is reported apart.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const M = [
  // rules
  ['src', "if (r === 'moved') { if (s.clock === 'tile') worldStep(s, d); return true; }", "if (r === 'moved') return true;", 'sim'],
  ['src', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (false) { kill(s, o, how); return true; }", 'sim'],
  ['src', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (['enemy', 'strong'].includes(o.kind)) { kill(s, o, how); return true; }", 'sim'],
  ['src', "} else if (e.kind === 'box' && (b = pushTo(s, nx, ny, t.d, false))) { if (land(s, e, b)) pushed = { id: e.id, d: b.d }; }", "} else if (false) {}", 'sim'],
  ['src', "if (e.kind === 'heavy' && CRUSHABLE.includes(o.kind)) kill(s, o, 'squash');", "if (false) kill(s, o, 'squash');", 'sim'],
  ['src', "if (e.kind === 'heavy' && CRUSHABLE.includes(o.kind)) kill(s, o, 'squash');", "if (e.kind === 'heavy' && ['enemy', 'strong'].includes(o.kind)) kill(s, o, 'squash');", 'sim'],
  ['src', "else { e.x = t.x; e.y = t.y; die(s); return; }", "else { e.dir = -e.dir; return; }", 'sim'],
  ['src', "pressed[col] = (pressed[col] ?? true) && down;", "pressed[col] = (pressed[col] ?? false) || down;", 'sim'],
  ['src', "const playerAt = (s, x, y) => !s.player.hidden && s.player.x === x", "const playerAt = (s, x, y) => s.player.x === x", 'sim'],
  ['src', "if (++p.hideTicks < HIDE_TICKS || s.entities.some(e => !e.dead && e.rush)) return;", "if (++p.hideTicks < HIDE_TICKS) return;", 'sim'],
  ['src', "crushes(s, e)) || solidCell(s, p.x, p.y)) {", "crushes(s, e))) {", 'sim'],
  ['src', "if (s.entities.some(e => !e.dead && e.x === p.x && e.y === p.y && crushes(s, e)) || solidCell", "if (solidCell", 'sim'],
  ['src', "if (!DIRS[k] || p.hidden) return;", "if (!DIRS[k]) return;", 'sim'],
  ['src', "if (p.dir || p.hidden) return;", "if (p.dir) return;", 'sim'],
  ['src', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "if (cellAt(s, x, y).startsWith('sensor:') && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", 'sim'],
  ['src', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "", 'sim'],
  ['src', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "", 'sim'],
  ['src', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "else if (c.startsWith('sensor:')) { col = c.slice(7); down = true; }", 'sim'],
  ['src', "if (c.startsWith('sensor:')) return COLOURS.includes(c.slice(7));", "", 'sim'],
  ['src', "if (s.tick % RT_PERIOD === RT_PERIOD - 1)", "if (false)", 'sim'],
  ['src', "    s.checkpoint = { x: nx, y: ny };\n", "", 'sim'],
  ['src', "for (const c of l.cells) if (!isCell(c)) throw new Error('Unknown tile: ' + c);", "", 'sim'],
  ['src', "if (moved > 0 && s.clock === 'slide')", "if (s.clock === 'slide')", 'sim'],
  ['src', "return !s.open[c.slice(5)];", "return false;", 'sim'],
  ['src', "  if (playerAt(s, t.x, t.y)) die(s);\n  else if (ridden", "  if (ridden", 'sim'],
  ['src', "if (o.kind === 'box' && (b = pushTo(s, t.x, t.y, t.d, false))) land(s, o, b);", "if (false) {}", 'sim'],
  ['src', "if (diving) { e.slide = t.d;", "if (false) { e.slide = t.d;", 'sim'],
  ['src', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (false) kill(s, e, 'dive');", 'sim'],
  ['src', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (ENEMY.includes(e.kind) && diving) kill(s, e, 'dive');", 'sim'],
  ['src', "dirs: CLOCKWISE.filter(d => e.turret.dirs.includes(d))", "dirs: e.turret.dirs", 'sim'],
  ['src', "|| new Set(t.dirs).size !== t.dirs.length)", ")", 'sim'],
  ['src', "if (moved > 0 && s.clock === 'slide') worldStep(s, d);", "if (moved > 0 && s.clock === 'slide') worldStep(s, 'up');", 'sim'],
  ['src', "if (!turned) moveMover(s, e, null, true);", "", 'sim'],
  ['src', "const blocked = () => { if (d) return;", "const blocked = () => {", 'sim'],
  ['src', "if (tri && !openFaces(tri).includes(ENTRY_FACE[d])) return null;", "", 'sim'],
  ['src', "  if (p.dir) p.dir = t.d;\n", "", 'sim'],
  ['src', "e.x = t.x; e.y = t.y; e.slide = t.d;", "e.x = t.x; e.y = t.y;", 'sim'],
  ['src', "if (c.startsWith('tri:')) return CORNERS.includes(c.slice(4));", "if (c.startsWith('tri:')) return true;", 'sim'],
  ['src', "return here && !openFaces(here).includes(EXIT_FACE[d]) ? turn(here, d) : d;", "return d;", 'sim'],
  ['src', "const aimOf = t => t.dirs[t.aim % t.dirs.length];", "const aimOf = t => t.dirs[0];", 'sim'],
  ['src', "    turnTurrets(s, 'realtime');\n", "", 'sim'],
  ['src', "e.turret.mode === 'follow' && e.turret.dirs.includes(d)) e.turret.aim = e.turret.dirs.indexOf(d);", "e.turret.mode === 'follow') e.turret.aim = Math.max(0, e.turret.dirs.indexOf(d));", 'sim'],
  ['src', "  computeBeams(s, true);\n", "", 'sim'],
  ['src', "if (harm && hitYou) die(s);", "", 'sim'],
  ['src', "if (r.stop && inb(s, ...r.stop) && cellAt(s, ...r.stop).startsWith('receiver:')) s.lit.add(r.stop[1] * s.w + r.stop[0]);", "", 'sim'],
  ['src', "else if (c.startsWith('receiver:')) { col = c.slice(9); down = s.lit.has(i); }", "else if (c.startsWith('receiver:')) { col = c.slice(9); down = true; }", 'sim'],
  ['src', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('spring:')) return true;", 'sim'],
  ['src', "if (c.startsWith('receiver:')) return COLOURS.includes(c.slice(9));", "if (c.startsWith('receiver:')) return true;", 'sim'],
  ['src', "    if (S.ui.tool === 'look') { $('placeHint').textContent = describe(S.level, c.x, c.y); return; }\n", "", 'browser'],
  ['src', "  if (m === 'edit') { S.ui.tool = 'look'; S.ui.group = 'basic'; }\n", "", 'phone'],
  ['src', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (to && !to.includes(d)) return null;", 'sim'],
  ['src', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (from && !from.includes(d)) return null;", 'sim'],
  ['src', "return ds.length > 0 && new Set(ds).size === ds.length && ds.every(d => CLOCKWISE.includes(d));", "return true;", 'sim'],
  ['src', "removePiece(); setCell('gate:' + CLOCKWISE.filter(d => ui.pass.includes(d)).join(','));", "removePiece(); setCell('gate:right');", 'browser'],
  ['src', "b.disabled = on && ui.pass.length === 1;", "b.disabled = false;", 'browser'],
  ['src', "if (cellAt(s, nx, ny) === 'death') return { x: nx, y: ny, d, death: true };", "", 'sim'],
  ['src', "  if (t.death) { die(s); return 'died'; }\n", "", 'sim'],
  ['src', "  if (t.death) { kill(s, e, 'death'); return false; }\n", "", 'sim'],
  ['src', "  if (t.death) { kill(s, e, 'death'); return; }\n  const o = entAt(s, t.x, t.y, e);\n  let b;", "  const o = entAt(s, t.x, t.y, e);\n  let b;", 'sim'],
  ['src', "  if (t.death) { kill(s, e, 'death'); return; }\n  const o = entAt(s, t.x, t.y, e);\n  if (o) {\n    if (e.kind === 'heavy'", "  const o = entAt(s, t.x, t.y, e);\n  if (o) {\n    if (e.kind === 'heavy'", 'sim'],
  ['src', "if (!t || t.death) { cd = facing", "if (!t) { cd = facing", 'sim'],
  ['src', "  fireSprings(s);\n", "", 'sim'],
  ['src', "if (playerAt(s, x, y) && p.dir !== d && stepTo(s, x, y, d, p.swimming)) {", "if (playerAt(s, x, y) && p.dir !== d) {", 'sim'],
  ['src', "if (e && e.kind !== 'turret' && e.slide !== d && stepTo(s, x, y, d, wades(e))) {", "if (false) {", 'sim'],
  ['src', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('receiver:')) return true;", 'sim'],
  ['src', "removePiece(); setCell(t === 'death' ? 'death' : 'spring:' + ui.face);", "removePiece(); setCell(t === 'death' ? 'death' : 'spring:up');", 'browser'],
  // page
  ['src', "if (host && (CARRIES_TURRET.includes(host.kind) || host.kind === 'turret')) {", "if (false) {", 'browser'],
  ['src', "b.disabled = on && ui.aim.length === 1;", "b.disabled = false;", 'browser'],
  ['src', "if (ui.mode === 'follow') $('axisOpt').hidden = true;", "", 'browser'],
  ['src', "S.painting = ev.button === 2 ? 'erase' : holds(S.level, c.x, c.y, S.ui.tool) && S.ui.tool !== 'start' ? 'remove' : 'place';", "S.painting = ev.button === 2 ? 'erase' : 'place';", 'browser'],
  ['src', "if (ui.tool === 'turret' && host && host.kind !== 'turret') { gone.piece = { ...host }; delete host.turret; }", "if (false) {}", 'browser'],
  ['src', "  if (how === 'remove' && !holds(level, x, y, ui.tool)) return out;\n", "", 'browser'],
  ['src', "removePiece(); setCell('tri:' + ui.corner);", "removePiece(); setCell('tri:se');", 'browser'],
  ['src', "if (d !== sw.last) S.pending.push(d);", "", 'phone'],
  ['src', "if (S.painting && c && S.ui.tool !== 'start') paint(c.x, c.y, S.painting);", "if (S.painting && S.hover && S.ui.tool !== 'start') paint(S.hover.x, S.hover.y, S.painting);", 'phone'],
  ['src', "$('hideBtn').onclick = () => S.pending.push('hide');", "", 'phone'],
  ['src', "const l = tall ? emptyLevel(12, 14) : emptyLevel(20, 12);", "const l = emptyLevel(20, 12);", 'phone'],
  ['src', "const zoom = Math.min(2.5, stage / (level.w * T), room / (level.h * T));", "const zoom = Math.max(1, Math.min(2.5, stage / (level.w * T), room / (level.h * T)));", 'phone'],
  ['src', "  for (const k of S.pending) S.keylog.push({ t: game.tick, k });\n", "", 'phone'],
  ['src', "S.played = JSON.parse(JSON.stringify(S.level)); S.keylog = [];", "S.played = S.level; S.keylog = [];", 'phone'],
  ['style.css', ".opt[hidden] { display: none; }", "", 'browser'],
  ['style.css', "grid-template-columns: 300px", "grid-template-columns: 200px", 'browser'],
  ['src', "a.download = 'room.wee';", "a.download = 'room.json';", 'browser'],
  ['src', "if (!ev.repeat) S.pending.push(k);", "", 'browser'],
  ['src', "if (t === 'erase') {\n    if (pi >= 0) removePiece(); else setCell('');", "if (t === 'erase') {", 'browser'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => true;", 'sim'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'heavy' || !s.powers.armored;", 'sim'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'strong' || !s.powers.armored;", 'sim'],
  ['src', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['heavy', 'mover'];", 'sim'],
  ['src', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['strong', 'heavy', 'mover', 'box', 'enemy'];", 'sim'],
  ['src', "|| (youIn(d) && s.powers.armored))) continue;", ")) continue;", 'sim'],
  ['src', "for (const e of inside(d)) kill(s, e, 'door');", "", 'sim'],
  ['src', "if (youIn(d) && !s.player.hidden) squashed = true;", "", 'sim'],
  ['src', "if (!crushes(s, e)) return 'blocked'; die(s); return 'died';", "die(s); return 'died';", 'sim'],
  ['src', "      if (!crushes(s, e)) { blocked(); return; }\n      e.x = t.x;", "      e.x = t.x;", 'sim'],
  ['src', "    else if (!crushes(s, e)) { blocked(); return; }\n", "", 'sim'],
  ['src', "(!crushes(s, e) || (e.kind !== 'heavy'", "((e.kind !== 'heavy'", 'sim'],
  ['src', "e.x === p.x && e.y === p.y && crushes(s, e))", "e.x === p.x && e.y === p.y)", 'sim'],
  ['src', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);", "drawPlayer(g, px, py, p.hidden, scale, 1, false, swim, p.sticky);", 'browser'],
  ['src', "if (!wet && cellAt(s, nx, ny) === 'water') return null;", "", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'mover'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['heavy', 'mover'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy', 'mover', 'enemy'];", 'sim'],
  ['src', "const p = s.player, t = stepTo(s, p.x, p.y, d, p.swimming);", "const p = s.player, t = stepTo(s, p.x, p.y, d);", 'sim'],
  ['src', "(b = pushTo(s, nx, ny, t.d, false))", "(b = pushTo(s, nx, ny, t.d))", 'sim'],
  ['src', "const swim = s.powers.swim && !inWater(s, p.x, p.y);", "const swim = s.powers.swim;", 'sim'],
  ['src', "if (!s.powers.cycle && !swim) return;", "", 'sim'],
  ['src', "if (s.powers.cycle) { p.hidden = true;", "if (true) { p.hidden = true;", 'sim'],
  ['src', "s.player.stroke = inWater(s, s.player.x, s.player.y) ? !s.player.stroke : false;", "s.player.stroke = false;", 'sim'],
  ['src', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "", 'sim'],
  ['src', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "for (const [dx, dy] of Object.values(DIRS)) if (inb(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", 'sim'],
  ['src', "return pools.has(s.player.y * s.w + s.player.x) && !s.player.hidden;", "return pools.has(s.player.y * s.w + s.player.x);", 'sim'],
  ['src', "for (const e of s.entities) if (!e.dead && pools.has(e.y * s.w + e.x)) laserHit(s, e, how);", "", 'sim'],
  ['src', "  if (harm && shockHarms(s, s.shocked, 'turret')) hitYou = true;\n", "", 'sim'],
  ['src', "  if (shockHarms(s, pools, 'laser')) die(s);\n", "", 'sim'],
  ['src', "if (c === 'death' || c === 'water' || c === 'sticky') return true;", "if (c === 'death' || c === 'sticky') return true;", 'sim'],
  ['src', "} else if (t === 'water' || t === 'sticky') {\n    if (isStart) return out;\n    setCell(t);", "} else if (false) {", 'browser'],
  ['src', "b.hidden = b.dataset.in !== ui.group;", "", 'phone'],
  ['src', "$('hideBtn').hidden = !tap.length; ", "", 'phone'],
  ['src', "$('hideBtn').textContent = tap.join(' / ');", "$('hideBtn').textContent = 'Hide / Swim';", 'phone'],
  ['src', "pending.push(`power:${p}:${box.checked ? 1 : 0}`); syncPanel(); };", "pending.push(`power:${p}:${box.checked ? 1 : 0}`); };", 'phone'],
  ['src', "if (m === 'edit') { S.ui.tool = 'look'; S.ui.group = 'basic'; }", "if (m === 'edit') { S.ui.tool = 'look'; }", 'phone'],
  ['style.css', "  #tools > h2:first-child { display: none; }\n", "", 'phone'],
  ['src', ": '')", ": 'Press Play to try this room.')", 'phone'],
  ['src', "if (c === 'sticky' && !p.stuck && !p.sticky) { p.sticky = true;", "if (false) { p.sticky = true;", 'sim'],
  ['src', "if (c === 'water') { p.sticky = false; unstick(s); }", "", 'sim'],
  ['src', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || e.kind === 'heavy';", 'sim'],
  ['src', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", 'sim'],
  ['src', "  p.sticky = false;\n  p.stuck = { id: e.id,", "  p.stuck = { id: e.id,", 'sim'],
  ['src', "ride: e.kind === 'mover' || !!e.slide,", "ride: e.kind === 'mover',", 'sim'],
  ['src', "if (!b) { unstick(s); return 'blocked'; }", "if (!b) { return 'blocked'; }", 'sim'],
  ['src', "} else if (e && p.sticky && STICKS(e)) { stick(s, e); return 'blocked'; }", "}", 'sim'],
  ['src', "if (g && !ahead) drag(s, g, dx, dy);", "", 'sim'],
  ['src', "if (g && !ahead) drag(s, g, dx, dy);", "if (g) drag(s, g, dx, dy);", 'sim'],
  ['src', "if (t) land(s, g, t);", "", 'sim'],
  ['src', "  if (p.stuck && p.stuck.ride) unstick(s);\n", "", 'sim'],
  ['src', "if (ridden && !pushed && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src', "if (!ridden) stick(s, e);", "", 'sim'],
  ['src', "if (playerAt(s, t.x, t.y) && (ridden || p.sticky) && !ENEMY.includes(e.kind)) {", "if (false) {", 'sim'],
  ['src', "else if (ridden && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src', "if (e.kind === 'box') st.ride = false; else unstick(s);", "unstick(s);", 'sim'],
  ['src', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", 'sim'],
  ['src', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || p.hidden) { unstick(s); return; }", 'sim'],
  ['src', "if (c === 'death' || c === 'water' || c === 'sticky') return true;", "if (c === 'death' || c === 'water') return true;", 'sim'],
  ['src', "  { id: 'sticky', label: 'Sticky puddle', group: 'tiles' },\n", "", 'browser'],
  ['style.css', "  .grid button[hidden] { display: flex; }\n", "", 'browser'],
  ['style.css', "  .tabs, #tools > h2:first-child { display: none; }\n", "", 'browser'],
  ['style.css', "  .ghead { display: block; }\n", "", 'browser'],
  ['src', "  s.entities = freshPieces(s.origin);\n", "", 'sim'],
  ['src', "  for (const e of s.entities) e.dead = true;\n", "", 'sim'],
  ['src', "if (s.powers.boomerang) { letGo(s); p.dir = k;", "if (s.powers.boomerang) { p.dir = k;", 'sim'],
  ['src', "{ if (land(s, e, b)) pushed = { id: e.id, d: b.d }; }", "land(s, e, b);", 'sim'],
  ['src', "  p.pushing = pushed;\n", "", 'sim'],
  ['src', "if (e && !e.slide) e.slide = pu.d;", "if (e && !e.slide) e.slide = OPPOSITE[pu.d];", 'sim'],
  ['src', "s.events.push({ type: 'boomerang', from: OPPOSITE[k] });", "s.events.push({ type: 'boomerang' });", 'browser'],
  ['src/rules/base.js', "// The rules' vocabulary", "import { T } from '../view/ink.js';\n// The rules' vocabulary", 'arch'],
  ['src/view/ink.js', "export const T = 32;", "export const T = 32;\n" + "//\n".repeat(300), 'arch'],
  ['src/app/main.js', "import { bindInput } from './input.js';\n", "", 'arch'],
  ['src', "if (e.rush || e.lastMove === s.move) return;", "if (e.rush) return;", 'sim'],
  ['src', "if (e.rush || e.lastMove === s.move) return;", "if (e.lastMove === s.move) return;", 'sim'],
  ['src', "    else if (e.mode === 'follow') launch(s, e, d);\n", "", 'sim'],
  ['src', "    if (e.mode === 'input') launch(s, e);\n", "", 'sim'],
  ['src', "moveMover(s, e, e.rushDir, true);", "moveMover(s, e, null, true);", 'sim'],
  ['src', "if (e.x === x && e.y === y) { e.rush = false; e.rushDir = null; }", "{ e.rush = false; e.rushDir = null; }", 'sim'],
  ['src', "  if (moved > 0) turnTurrets(s, 'input');\n", "", 'sim'],
  ['src', "e.slide = d; e.rush = false; e.rushDir = null;", "e.slide = d;", 'sim'],
  ['src', "&& !e.rush && e.mode === 'realtime' && MOVES.includes(e.kind)) e.rush = true;", "&& !e.rush && e.mode === 'realtime' && MOVES.includes(e.kind)) {}", 'sim'],
  ['src', "if (!p.dir) { p.dir = k; p.moved = 0; s.move++; return; }", "if (!p.dir) { p.dir = k; p.moved = 0; return; }", 'sim'],
  ['src', "  s.move++;\n  for (const e of s.entities) if (!e.dead && e.mode === 'input'", "  for (const e of s.entities) if (!e.dead && e.mode === 'input'", 'sim'],
  ['src', "return side && p.from && alpha < 0.5 ? 'back:' + k : k;", "return k;", 'sim'],
  ['src', "return side && p.from && alpha < 0.5 ? 'back:' + k : k;", "return side && p.from ? 'back:' + k : k;", 'sim'],
  ['src', "const side = p.dir && DIRS[k] && k !== p.dir && k !== OPPOSITE[p.dir];", "const side = p.dir && DIRS[k];", 'sim'],
  ['src', "const o = from || s.player;", "const o = s.player;", 'sim'],
  ['src', "  p.from = { x: p.x, y: p.y };\n", "", 'sim'],
  ['src', "if (!ev.repeat) S.pending.push(aim(k));", "if (!ev.repeat) S.pending.push(k);", 'browser'],
  ['src', "const CRUSHABLE = ['enemy', 'strong', 'box'];", "const CRUSHABLE = ['enemy', 'strong'];", 'sim'],
  ['src', "  if (c.startsWith('idoor:')) return !!s.open[c.slice(6)];\n", "", 'sim'],
  ['src', "if (c.startsWith('idoor:')) return !!s.open[c.slice(6)];", "if (c.startsWith('idoor:')) return !s.open[c.slice(6)];", 'sim'],
  ['src', "if (want !== !!s.open[col]) {", "if (!want && s.open[col]) {", 'sim'],
  ['src', "const closing = (want ? 'idoor:' : 'door:') + col, doors = [];", "const closing = 'door:' + col, doors = [];", 'sim'],
  ['src', "(kind === 'button' || kind === 'door' || kind === 'idoor')", "(kind === 'button' || kind === 'door')", 'sim'],
  ['src', "const isDoor = c => c.startsWith('door:') || c.startsWith('idoor:');", "const isDoor = c => c.startsWith('door:');", 'sim'],
  ['src', "const solid = t === 'door' || t === 'idoor' || t === 'receiver';", "const solid = t === 'door' || t === 'receiver';", 'sim'],
  ['src', "    else if (kind === 'idoor') parts.push(`${COLOUR_NAME[v]} inverted door`);\n", "", 'sim'],
  ['src', "tool === 'receiver' || tool === 'sensor' || tool === 'gate') return", "tool === 'receiver' || tool === 'gate') return", 'browser'],
  ['src', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);\n  g.restore();", "g.restore();", 'browser'],
];

let caught = 0, crashed = 0;
// 'src' as the file means: whichever source file holds the text, which must be exactly one.
const walk = d => readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(d + '/' + e.name) : /\.js$/.test(e.name) ? [d + '/' + e.name] : []);
const locate = (file, from) => {
  if (file !== 'src') return readFileSync(file, 'utf8').includes(from) ? file : null;
  const hits = walk('src').filter(f => readFileSync(f, 'utf8').includes(from));
  return hits.length === 1 ? hits[0] : null;
};
for (const [where, from, to, test] of M) {
  if (process.env.ONLY && !from.includes(process.env.ONLY)) { caught++; continue; }
  const file = locate(where, from);
  if (!file) { console.log(`STALE mutant in ${where}: ${from.slice(0, 50)}`); process.exitCode = 1; continue; }
  if (process.env.STALE_ONLY) { caught++; continue; }
  const orig = readFileSync(file, 'utf8');
  writeFileSync(file, orig.replace(from, to));
  try {
    const r = spawnSync('node', [`tests/${test}.${['sim', 'arch'].includes(test) ? 'test' : 'smoke'}.mjs`], { encoding: 'utf8' });
    const out = r.stdout + r.stderr;
    const fail = out.split('\n').find(l => l.startsWith('FAIL'));
    if (fail) { caught++; console.log(`caught  ${fail.slice(0, 90)}`); }
    else if (r.status !== 0) { crashed++; console.log(`CRASHED ${file}: ${from.slice(0, 50)}`); }
    else console.log(`SURVIVED ${file}: ${from.slice(0, 60)}`);
  } finally { writeFileSync(file, orig); }
}
console.log(`mutants: ${caught}/${M.length} caught${crashed ? `, ${crashed} crashed` : ''}`);
process.exit(caught === M.length ? 0 : 1);
