// Breaks one rule at a time and requires the suite to notice. A mutant counts as
// caught only when a check prints FAIL; a crash with no FAIL line is reported apart.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const M = [
  // rules
  ['src', "    if (s.clock === 'tile') worldStep(s, d);\n    return true;", "    return true;", 'sim'],
  ['src', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (false) { kill(s, o, how); return true; }", 'sim'],
  ['src', "if (o.kind === 'enemy') { kill(s, o, how); return true; }", "if (['enemy', 'strong'].includes(o.kind)) { kill(s, o, how); return true; }", 'sim'],
  ['src', "    } else if (e.kind === 'box') {\n      // A box glued", "    } else if (false) {\n      // A box glued", 'sim'],
  ['src', "if (e.kind === 'heavy' && CRUSHABLE.includes(o.kind)) kill(s, o, 'squash');", "if (false) kill(s, o, 'squash');", 'sim'],
  ['src', "if (e.kind === 'heavy' && CRUSHABLE.includes(o.kind)) kill(s, o, 'squash');", "if (e.kind === 'heavy' && ['enemy', 'strong'].includes(o.kind)) kill(s, o, 'squash');", 'sim'],
  ['src', "else { e.x = t.x; e.y = t.y; die(s); return; }", "else { e.dir = -e.dir; return; }", 'sim'],
  ['src', "pressed[col] = (pressed[col] ?? true) && down;", "pressed[col] = (pressed[col] ?? false) || down;", 'sim'],
  ['src', "const playerAt = (s, x, y) => !s.player.hidden && s.player.x === x", "const playerAt = (s, x, y) => s.player.x === x", 'sim'],
  ['src', "if (++p.hideTicks < HIDE_TICKS || s.entities.some(e => !e.dead && e.rush)) return;", "if (++p.hideTicks < HIDE_TICKS) return;", 'sim'],
  ['src', "crushes(s, e)) || solidCell(s, p.x, p.y)) {", "crushes(s, e))) {", 'sim'],
  ['src', "if (s.entities.some(e => !e.dead && e.x === p.x && e.y === p.y && crushes(s, e)) || solidCell", "if (solidCell", 'sim'],
  ['src', "if (!DIRS[k] || p.hidden) return;", "if (!DIRS[k]) return;", 'sim'],
  ['src', "if (p.dir || p.hidden) return;", "if (p.dir) return;", 'sim'],
  ['src', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "if (cellAt(s, x, y).startsWith('sensor:') && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", 'sim'],
  ['src', "if (cellAt(s, x, y).startsWith('sensor:') && !entAt(s, x, y) && !playerAt(s, x, y)) s.lit.add(y * s.w + x);", "", 'sim'],
  ['src', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "", 'sim'],
  ['src', "else if (c.startsWith('sensor:')) { col = c.slice(7); down = s.lit.has(i); }", "else if (c.startsWith('sensor:')) { col = c.slice(7); down = true; }", 'sim'],
  ['src', "if (c.startsWith('sensor:')) return COLOURS.includes(c.slice(7));", "", 'sim'],
  ['src', "if (s.tick % RT_PERIOD === RT_PERIOD - 1)", "if (false)", 'sim'],
  ['src', "    s.checkpoint = { x: nx, y: ny };\n", "", 'sim'],
  ['src', "for (const c of l.cells) if (!isCell(c)) throw new Error('Unknown tile: ' + c);", "", 'sim'],
  ['src', "if (s.player.moved === 1) { turnTurrets(s, 'input'); if (s.clock === 'slide') worldStep(s, d); }", "if (s.player.moved === 1) turnTurrets(s, 'input');", 'sim'],
  ['src', "return !s.open[c.slice(5)];", "return false;", 'sim'],
  ['src', "  if (playerAt(s, t.x, t.y)) die(s);\n  else if (ridden", "  if (ridden", 'sim'],
  ['src', "if (o.kind === 'box' && (b = pushTo(s, t.x, t.y, t.d, false))) { if (land(s, o, b)) follow(s, o, mx, my); }", "if (false) {}", 'sim'],
  ['src', "if (diving) { e.slide = t.d;", "if (false) { e.slide = t.d;", 'sim'],
  ['src', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (false) kill(s, e, 'dive');", 'sim'],
  ['src', "if (e.kind === 'enemy' && diving) kill(s, e, 'dive');", "if (ENEMY.includes(e.kind) && diving) kill(s, e, 'dive');", 'sim'],
  ['src', "dirs: CLOCKWISE.filter(d => e.turret.dirs.includes(d))", "dirs: e.turret.dirs", 'sim'],
  ['src', "|| new Set(t.dirs).size !== t.dirs.length)", ")", 'sim'],
  ['src', "if (s.clock === 'slide') worldStep(s, d); }", "if (s.clock === 'slide') worldStep(s, 'up'); }", 'sim'],
  ['src', "const blocked = () => { e.dir = -e.dir; };", "const blocked = () => {};", 'sim'],
  ['src', "if (tri && !openFaces(tri).includes(ENTRY_FACE[d])) return null;", "", 'sim'],
  ['src', "  if (p.dir) p.dir = t.d;\n", "", 'sim'],
  ['src', "land(s, e, t); e.slide = t.d;\n", "land(s, e, t);\n", 'sim'],
  ['src', "if (c.startsWith('tri:')) return CORNERS.includes(c.slice(4));", "if (c.startsWith('tri:')) return true;", 'sim'],
  ['src', "return here && !openFaces(here).includes(EXIT_FACE[d]) ? turn(here, d) : d;", "return d;", 'sim'],
  ['src', "const aimOf = t => t.dirs[t.aim % t.dirs.length];", "const aimOf = t => t.dirs[0];", 'sim'],
  ['src', "    turnTurrets(s, 'realtime');\n", "", 'sim'],
  ['src', "e.turret.mode === 'follow' && e.turret.dirs.includes(d)) e.turret.aim = e.turret.dirs.indexOf(d);", "e.turret.mode === 'follow') e.turret.aim = Math.max(0, e.turret.dirs.indexOf(d));", 'sim'],
  ['src', "  computeBeams(s, true);\n", "", 'sim'],
  ['src', "if (harm && hitYou) die(s);", "", 'sim'],
  ['src', "if (r.stop && inb(s, ...r.stop) && cellAt(s, ...r.stop).startsWith('receiver:')) s.lit.add(r.stop[1] * s.w + r.stop[0]);", "", 'sim'],
  ['src', "else if (c.startsWith('receiver:')) { col = c.slice(9); down = s.lit.has(i); }", "else if (c.startsWith('receiver:')) { col = c.slice(9); down = true; }", 'sim'],
  ['src', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('spring:')) return true;", 'sim'],
  ['src', "if (c.startsWith('receiver:')) return COLOURS.includes(c.slice(9));", "if (c.startsWith('receiver:')) return true;", 'sim'],
  ['src', "      $('placeHint').textContent = describe(S.level, c.x, c.y);\n", "", 'browser'],
  ['src', "  if (m === 'edit') { S.ui.tool = 'look'; S.ui.group = 'basic'; }\n", "", 'phone'],
  ['src', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (to && !to.includes(d)) return null;", 'sim'],
  ['src', "if ((from && !from.includes(d)) || (to && !to.includes(d))) return null;", "if (from && !from.includes(d)) return null;", 'sim'],
  ['src', "return ds.length > 0 && new Set(ds).size === ds.length && ds.every(d => CLOCKWISE.includes(d));", "return true;", 'sim'],
  ['src', "removePiece(); setCell('gate:' + CLOCKWISE.filter(d => ui.pass.includes(d)).join(','));", "removePiece(); setCell('gate:right');", 'browser'],
  ['src', "b.disabled = on && ui.pass.length === 1;", "b.disabled = false;", 'browser'],
  ['src', "if (cellAt(s, nx, ny) === 'death') return { x: nx, y: ny, d, death: true };", "", 'sim'],
  ['src', "  if (t.death) { die(s); return 'died'; }\n", "", 'sim'],
  ['src', "  if (t.death) { kill(s, e, 'death'); return false; }\n", "", 'sim'],
  ['src', "if (!t || t.death) { cd = facing", "if (!t) { cd = facing", 'sim'],
  ['src', "  fireSprings(s);\n", "", 'sim'],
  ['src', "if (playerAt(s, x, y) && p.dir !== d && stepTo(s, x, y, d, p.swimming)) {", "if (playerAt(s, x, y) && p.dir !== d) {", 'sim'],
  ['src', "if (e && e.kind !== 'turret' && e.slide !== d && stepTo(s, x, y, d, wades(e))) {", "if (false) {", 'sim'],
  ['src', "if (c === 'wall' || c.startsWith('receiver:') || c.startsWith('spring:')) return true;", "if (c === 'wall' || c.startsWith('receiver:')) return true;", 'sim'],
  ['src', "removePiece(); setCell(t === 'death' ? 'death' : 'spring:' + ui.face);", "removePiece(); setCell(t === 'death' ? 'death' : 'spring:up');", 'browser'],
  // page
  ['src', "if (host && (CARRIES_TURRET.includes(host.kind) || host.kind === 'turret')) {", "if (false) {", 'browser'],
  ['src', "b.disabled = on && ui.aim.length === 1;", "b.disabled = false;", 'browser'],
  ['src', "if (ui.mode === 'follow') $('axisOpt').hidden = true;", "", 'browser'],
  ['src', "S.painting = ev.button === 2 ? 'erase' : holds(S.level, c.x, c.y, S.ui.tool) && S.ui.tool !== 'start' ? 'remove' : 'place';", "S.painting = ev.button === 2 ? 'erase' : 'place';", 'browser'],
  ['src', "if (ui.tool === 'turret' && host && host.kind !== 'turret') { gone.piece = { ...host }; delete host.turret; }", "if (false) {}", 'browser'],
  ['src', "  if (how === 'remove' && !holds(level, x, y, ui.tool)) return out;\n", "", 'browser'],
  ['src', "removePiece(); setCell('tri:' + ui.corner);", "removePiece(); setCell('tri:se');", 'browser'],
  ['src', "if (d !== sw.last) S.pending.push(aim(d));", "", 'phone'],
  ['src', "if (S.painting && c && S.ui.tool !== 'start') paint(c.x, c.y, S.painting);", "if (S.painting && S.hover && S.ui.tool !== 'start') paint(S.hover.x, S.hover.y, S.painting);", 'phone'],
  ['src', "$('hideBtn').onclick = () => S.pending.push('hide');", "", 'phone'],
  ['src', "const l = tall ? emptyLevel(12, 14) : emptyLevel(20, 12);", "const l = emptyLevel(20, 12);", 'phone'],
  ['src', "const zoom = Math.min(2.5, stage / (level.w * T), room / (level.h * T));", "const zoom = Math.max(1, Math.min(2.5, stage / (level.w * T), room / (level.h * T)));", 'phone'],
  ['src', "  for (const k of S.pending) S.keylog.push({ t: game.tick, k });\n", "", 'phone'],
  ['src', "S.played = JSON.parse(JSON.stringify(from)); S.keylog = [];", "S.played = from; S.keylog = [];", 'phone'],
  ['style.css', ".opt[hidden] { display: none; }", "", 'browser'],
  ['style.css', "grid-template-columns: 300px", "grid-template-columns: 200px", 'browser'],
  ['src', "download(($('roomName').value.trim() || 'room').replace(/[^\\w-]+/g, '-') + '.wee',", "download('room.json',", 'browser'],
  ['src', "if (!ev.repeat) { S.demo = null; S.demoWait = null; S.pending.push(aim(k)); }", "", 'browser'],
  ['src', "if (t === 'erase') {\n    if (pi >= 0) removePiece(); else setCell('');", "if (t === 'erase') {", 'browser'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => true;", 'sim'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'heavy' || !s.powers.armored;", 'sim'],
  ['src', "const crushes = (s, e) => e.kind === 'heavy' || e.kind === 'strong' || !s.powers.armored;", "const crushes = (s, e) => e.kind === 'strong' || !s.powers.armored;", 'sim'],
  ['src', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['heavy', 'mover'];", 'sim'],
  ['src', "const HOLDS_DOOR = ['strong', 'heavy', 'mover'];", "const HOLDS_DOOR = ['strong', 'heavy', 'mover', 'box', 'enemy'];", 'sim'],
  ['src', "|| (youIn(d) && s.powers.armored))) continue;", ")) continue;", 'sim'],
  ['src', "for (const e of inside(d)) kill(s, e, 'door');", "", 'sim'],
  ['src', "if (youIn(d) && !s.player.hidden) squashed = true;", "", 'sim'],
  ['src', "if (!crushes(s, e)) return 'blocked'; die(s); return 'died';", "die(s); return 'died';", 'sim'],
  ['src', "      if (!crushes(s, e)) { blocked(); return; }\n      e.x = t.x;", "      e.x = t.x;", 'sim'],
  ['src', "    else if (!crushes(s, e)) { blocked(); return; }\n", "", 'sim'],
  ['src', "(!crushes(s, e) || (e.kind !== 'heavy'", "((e.kind !== 'heavy'", 'sim'],
  ['src', "e.x === p.x && e.y === p.y && crushes(s, e))", "e.x === p.x && e.y === p.y)", 'sim'],
  ['src', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);", "drawPlayer(g, px, py, p.hidden, scale, 1, false, swim, p.sticky);", 'browser'],
  ['src', "if (!wet && cellAt(s, nx, ny) === 'water') return null;", "", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'mover'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['heavy', 'mover'];", 'sim'],
  ['src', "const WADES = ['strong', 'heavy', 'mover'];", "const WADES = ['strong', 'heavy', 'mover', 'enemy'];", 'sim'],
  ['src', "const p = s.player, t = stepTo(s, p.x, p.y, d, p.swimming);", "const p = s.player, t = stepTo(s, p.x, p.y, d);", 'sim'],
  ['src', "(b = pushTo(s, nx, ny, t.d, false))", "(b = pushTo(s, nx, ny, t.d))", 'sim'],
  ['src', "const swim = s.powers.swim && !inWater(s, p.x, p.y);", "const swim = s.powers.swim;", 'sim'],
  ['src', "if (!s.powers.cycle && !swim) return;", "", 'sim'],
  ['src', "if (s.powers.cycle) { p.hidden = true;", "if (true) { p.hidden = true;", 'sim'],
  ['src', "s.player.stroke = inWater(s, s.player.x, s.player.y) ? !s.player.stroke : false;", "s.player.stroke = false;", 'sim'],
  ['src', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "", 'sim'],
  ['src', "for (const [dx, dy] of Object.values(DIRS)) if (inWater(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", "for (const [dx, dy] of Object.values(DIRS)) if (inb(s, x + dx, y + dy)) todo.push((y + dy) * s.w + x + dx);", 'sim'],
  ['src', "return pools.has(s.player.y * s.w + s.player.x) && !s.player.hidden;", "return pools.has(s.player.y * s.w + s.player.x);", 'sim'],
  ['src', "for (const e of s.entities) if (!e.dead && pools.has(e.y * s.w + e.x)) laserHit(s, e, how);", "", 'sim'],
  ['src', "  if (harm && shockHarms(s, s.shocked, 'turret')) hitYou = true;\n", "", 'sim'],
  ['src', "  if (shockHarms(s, pools, 'laser')) die(s);\n", "", 'sim'],
  ['src', "if (c === 'death' || c === 'water' || c === 'sticky' || c === 'goal') return true;", "if (c === 'death' || c === 'sticky' || c === 'goal') return true;", 'sim'],
  ['src', "} else if (t === 'water' || t === 'sticky' || t === 'goal') {\n    if (isStart) return out;\n    setCell(t);", "} else if (false) {", 'browser'],
  ['src', "b.hidden = b.dataset.in !== ui.group;", "", 'phone'],
  ['src', "$('hideBtn').hidden = !tap.length; ", "", 'phone'],
  ['src', "$('hideBtn').textContent = tap.join(' / ');", "$('hideBtn').textContent = 'Hide / Swim';", 'phone'],
  ['src', "pending.push(`power:${p}:${box.checked ? 1 : 0}`); syncPanel(); };", "pending.push(`power:${p}:${box.checked ? 1 : 0}`); };", 'phone'],
  ['src', "if (m === 'edit') { S.ui.tool = 'look'; S.ui.group = 'basic'; }", "if (m === 'edit') { S.ui.tool = 'look'; }", 'phone'],
  ['style.css', "  #tools > h2:first-child { display: none; }\n", "", 'phone'],
  ['src', "use a power.' : '')", "use a power.' : 'Press Play to try this room.')", 'phone'],
  ['src', "if (c === 'sticky' && !p.stuck && !p.sticky) { p.sticky = true;", "if (false) { p.sticky = true;", 'sim'],
  ['src', "if (c === 'water') { p.sticky = false; unstick(s); }", "", 'sim'],
  ['src', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || e.kind === 'heavy';", 'sim'],
  ['src', "const STICKS = e => e.kind === 'mover' || e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", "const STICKS = e => e.kind === 'box' || (e.kind === 'heavy' && !!e.slide);", 'sim'],
  ['src', "  p.sticky = false;\n  p.stuck = { id: e.id,", "  p.stuck = { id: e.id,", 'sim'],
  ['src', "ride: e.kind === 'mover' || !!e.slide,", "ride: e.kind === 'mover',", 'sim'],
  ['src', "if (!b) { unstick(s); return 'blocked'; }", "if (!b) { return 'blocked'; }", 'sim'],
  ['src', "} else if (e && p.sticky && STICKS(e)) { stick(s, e); return 'blocked'; }", "}", 'sim'],
  ['src', "if (g && !ahead) drag(s, g, dx, dy);", "", 'sim'],
  ['src', "if (g && !ahead) drag(s, g, dx, dy);", "if (g) drag(s, g, dx, dy);", 'sim'],
  ['src', "if (t) land(s, g, t);", "", 'sim'],
  ['src', "  if (p.stuck && p.stuck.ride) unstick(s);\n", "", 'sim'],
  ['src', "if (ridden && !pushed && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src', "if (!ridden) stick(s, e);", "", 'sim'],
  ['src', "if (playerAt(s, t.x, t.y) && (ridden || p.sticky) && !ENEMY.includes(e.kind)) {", "if (false) {", 'sim'],
  ['src', "else if (ridden && stuckTo(s) === e) carry(s, mx, my);", "", 'sim'],
  ['src', "if (e.kind === 'box') st.ride = false; else unstick(s);", "unstick(s);", 'sim'],
  ['src', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", 'sim'],
  ['src', "if (!e || p.hidden || e.x !== p.x + st.dx || e.y !== p.y + st.dy) { unstick(s); return; }", "if (!e || p.hidden) { unstick(s); return; }", 'sim'],
  ['src', "if (c === 'death' || c === 'water' || c === 'sticky' || c === 'goal') return true;", "if (c === 'death' || c === 'water' || c === 'goal') return true;", 'sim'],
  ['src', "  { id: 'sticky', label: 'Sticky puddle', group: 'tiles' },\n", "", 'browser'],
  ['style.css', "  .grid button[hidden] { display: flex; }\n", "", 'browser'],
  ['style.css', "  .tabs, #tools > h2:first-child { display: none; }\n", "", 'browser'],
  ['style.css', "  .ghead { display: block; }\n", "", 'browser'],
  ['src', "  s.entities = freshPieces(s.origin);\n", "", 'sim'],
  ['src', "  for (const e of s.entities) e.dead = true;\n", "", 'sim'],
  ['src', "if (s.powers.boomerang) { letGo(s); p.dir = k;", "if (s.powers.boomerang) { p.dir = k;", 'sim'],
  ['src', "if (land(s, e, b)) { pushed = { id: e.id, d: b.d }; if (!led)", "if (land(s, e, b)) { if (!led)", 'sim'],
  ['src', "  p.pushing = pushed;\n", "", 'sim'],
  ['src', "if (e && !e.slide) e.slide = pu.d;", "if (e && !e.slide) e.slide = OPPOSITE[pu.d];", 'sim'],
  ['src', "s.events.push({ type: 'boomerang', from: OPPOSITE[k] });", "s.events.push({ type: 'boomerang' });", 'browser'],
  ['src/rules/base.js', "// The rules' vocabulary", "import { T } from '../view/ink.js';\n// The rules' vocabulary", 'arch'],
  ['src/view/ink.js', "export const T = 32;", "export const T = 32;\n" + "//\n".repeat(300), 'arch'],
  ['src/app/main.js', "import { bindInput } from './input.js';\n", "", 'arch'],
  ['src', "if (e.rush || e.lastMove === s.move || partnerOf(s, e)?.rush) return;", "if (e.rush || partnerOf(s, e)?.rush) return;", 'sim'],
  ['src', "if (e.rush || e.lastMove === s.move || partnerOf(s, e)?.rush) return;", "if (e.lastMove === s.move || partnerOf(s, e)?.rush) return;", 'sim'],
  ['src', "    else if (e.mode === 'follow') launch(s, e, d);\n", "", 'sim'],
  ['src', "    if (e.mode === 'input') launch(s, e);\n", "", 'sim'],
  ['src', "moveMover(s, e, e.rushDir);", "moveMover(s, e, null, true);", 'sim'],
  ['src', "if (e.x === x && e.y === y) { e.rush = false; e.rushDir = null; }", "{ e.rush = false; e.rushDir = null; }", 'sim'],
  ['src', "if (s.player.moved === 1) { turnTurrets(s, 'input'); if", "if (s.player.moved === 1) { if", 'sim'],
  ['src', "if (s.player.moved === 1) { turnTurrets", "if (s.player.moved >= 1) { turnTurrets", 'sim'],
  ['src', "e.slide = d; e.rush = false; e.rushDir = null;", "e.slide = d;", 'sim'],
  ['src', "&& !e.rush && e.mode === 'realtime' && MOVES.includes(e.kind) && !partnerOf(s, e)?.rush) e.rush = true;", "&& !e.rush && e.mode === 'realtime' && MOVES.includes(e.kind) && !partnerOf(s, e)?.rush) {}", 'sim'],
  ['src', "if (!p.dir) { p.dir = k; p.moved = 0; s.move++; return; }", "if (!p.dir) { p.dir = k; p.moved = 0; return; }", 'sim'],
  ['src', "  s.move++;\n  for (const e of s.entities) if (!e.dead && e.mode === 'input'", "  for (const e of s.entities) if (!e.dead && e.mode === 'input'", 'sim'],
  ['src', "return side && p.from && alpha < 0.5 ? 'back:' + k : k;", "return k;", 'sim'],
  ['src', "return side && p.from && alpha < 0.5 ? 'back:' + k : k;", "return side && p.from ? 'back:' + k : k;", 'sim'],
  ['src', "const side = p.dir && DIRS[k] && k !== p.dir && k !== OPPOSITE[p.dir];", "const side = p.dir && DIRS[k];", 'sim'],
  ['src', "const o = from || s.player;", "const o = s.player;", 'sim'],
  ['src', "  p.from = { x: p.x, y: p.y };\n", "", 'sim'],
  ['src', "if (!ev.repeat) { S.demo = null; S.demoWait = null; S.pending.push(aim(k)); }", "if (!ev.repeat) { S.demo = null; S.demoWait = null; S.pending.push(k); }", 'browser'],
  ['src', "const CRUSHABLE = ['enemy', 'strong', 'box'];", "const CRUSHABLE = ['enemy', 'strong'];", 'sim'],
  ['src', "    for (; i < saved.length && performance.now() < until; i++) {", "    for (; i < saved.length; i++) {", "perf"],
  ["src", "    if (my !== building) return;\n", "", "perf"],
  ['src', "  if (S.mode === 'play' || editNeedsDraw(t)) { render();", "  if (true) { render();", "perf"],
  ['src', "  return t - (S.drawnAt || 0) > AMBIENT_MS && S.level.cells.some(c => ANIMATED.test(c));", "  return false;", "perf"],
  ['src', "        yield r ? [`${d}@${i}:${then}`, r] : null;", "        if (r) yield [`${d}@${i}:${then}`, r];", "perf"],
  ['src', "it = reach(JSON.parse(stamp), { budgetMs: STOPS_BUDGET_MS, out });", "it = reach(JSON.parse(stamp), { out });", "perf"],
  ['src', "  if (!thumbs.has(version)) thumbs.set(version, thumbURL(level));", "  thumbs.set(version, thumbURL(level));", "perf"],
  ['src', "  clearDraft();\n  saved = [stored, ...saved.filter(o => o.id !== stored.id)];", "  saved = [stored, ...saved.filter(o => o.id !== stored.id)];", "browser"],
  ['src', "export function syncRoomsButton() {\n  noteChange(dirty());", "export function syncRoomsButton() {", "browser"],
  ['src', "  if (d && d.level) {", "  if (false) {", "browser"],
  ['src', "g.fillStyle = traps && traps.has(i) ? INK.beam : INK.player;", "g.fillStyle = INK.player;", 'designui'],
  ['src', "  if (kind === 'spring') return 'spring:' + cw(v);", "  if (kind === 'spring') return c;", "region"],
  ['src', "  if (kind === 'tri') return 'tri:' + CORNER_CW[v];", "  if (kind === 'tri') return c;", "region"],
  ['src', "    t.dir = e.axis === 'h' ? (e.dir || 1) : -(e.dir || 1);", "    t.dir = e.dir || 1;", "region"],
  ['src', "  if (e.turret) t.turret = { ...e.turret, dirs: CLOCKWISE.filter(d => e.turret.dirs.map(cw).includes(d)) };\n", "", "region"],
  ['src', "    if (inside(cx, cy) && !(isStart(cx, cy) && clip.cells[j * clip.w + i])) cells[cy * level.w + cx] = clip.cells[j * clip.w + i];", "    if (inside(cx, cy)) cells[cy * level.w + cx] = clip.cells[j * clip.w + i];", "region"],
  ['src', "  return { ...level, cells, entities: [...level.entities.filter(e => !taken.has(e.x + ',' + e.y)), ...placed] };", "  return { ...level, cells, entities: [...level.entities, ...placed] };", "region"],
  ['src', "  const entities = level.entities.filter(e => inR(r, e.x, e.y)).map(e => ({ ...JSON.parse(JSON.stringify(e)), x: e.x - r.x0, y: e.y - r.y0 }));", "  const entities = level.entities.filter(e => inR(r, e.x, e.y)).map(e => Object.assign(e, { x: e.x - r.x0, y: e.y - r.y0 }));", "region"],
  ['src', "  if (S.paste) { change(() => { S.level = pasteRegion(S.level, S.paste, c.x, c.y); }); A.syncPanel(); return; }", "  if (S.paste) return;", "browser"],
  ['src', "  change(() => { S.level = pasteRegion(clearRegion(S.level, r), turned, r.x0, r.y0); });", "  change(() => { S.level = pasteRegion(S.level, turned, r.x0, r.y0); });", "browser"],
  ['src', "    if (S.ui.tool === 'select') { canvas.setPointerCapture(ev.pointerId); S.hover = c; selectDown(c); return; }", "    if (false) { canvas.setPointerCapture(ev.pointerId); S.hover = c; selectDown(c); return; }", "browser"],
  ['src', "    if (S.mode === 'edit' && selectKey(ev)) return;\n", "", "browser"],
  ['src', "  code = code.trim().replace(/^.*#room=/, '');", "  code = code.trim();", "code"],
  ['src', "  if (!code.startsWith('w1')) throw new Error('Not a wee room code.');\n", "", "code"],
  ['src', "  return parseLevel(text);", "  return JSON.parse(text);", "code"],
  ['src', "  const { format, version, w, h, cells, start, entities, powers, clock } = level;\n  const text = JSON.stringify({ format, version, w, h, cells, start, entities, powers, clock });", "  const text = JSON.stringify(level);", "code"],
  ['src', "    catch { $('codeIn').value = text; $('codeIn').select(); say('Copy it from the box.'); }", "    catch { say('Copy it from the box.'); }", "browser"],
  ['src', "      history.replaceState(null, '', location.pathname + location.search);\n", "", "browser"],
  ['src', "  if (location.hash.startsWith('#room=')) {", "  if (false) {", "browser"],
  ['src', "        stops.add(t.player.y * t.w + t.player.x);\n", "", "solve"],
  ['src', "  if (unsearchable({ ...level, cells: [...level.cells, 'goal'] })) return { why: 'realtime', stops: [] };\n", "", "solve"],
  ['src', "          if (seen.size >= max || performance.now() > until) { capped = true; break; }", "          if (performance.now() > until) { capped = true; break; }", "solve"],
  ['src', "      const open = !/^(wall|receiver:|spring:|door:|idoor:|death)/.test(cell) && !S.level.entities.some(e => e.x === c.x && e.y === c.y);", "      const open = true;", "browser"],
  ['src', "  const from = m === 'play' && S.playFrom ? { ...S.level, start: S.playFrom } : S.level;", "  const from = S.level;", "browser"],
  ['src', "  if (stops) for (const i of stops) {", "  if (stops) for (const i of []) {", "browser"],
  ['src', "  if (S.stops) { S.stops = null;", "  if (false) { S.stops = null;", "browser"],
  ['src', "  const dx = side === 'left' ? delta : 0, dy = side === 'top' ? delta : 0;", "  const dx = 0, dy = 0;", "sim"],
  ['src', "  if (w < 3 || h < 3 || w > 40 || h > 30) return null;", "  if (w > 40 || h > 30) return null;", "sim"],
  ['src', "  if (!inside(start.x, start.y)) return null;\n", "", "sim"],
  ['src', ".filter(e => inside(e.x, e.y));\n  return { ...level, w, h, cells, start, entities };", ";\n  return { ...level, w, h, cells, start, entities };", "sim"],
  ['src', "    if ((x === 0 || y === 0 || x === w - 1 || y === h - 1) && !(x === level.start.x && y === level.start.y)) cells[i] = 'wall';", "    if (x === 0 || y === 0 || x === w - 1 || y === h - 1) cells[i] = 'wall';", "sim"],
  ['src', "  return { ...level, cells, entities: level.entities.filter(e => !edge(e)) };", "  return { ...level, cells };", "sim"],
  ['src', "    if (!l) { $('placeHint').textContent = 'That cut would remove the start, or make the room too small.'; return; }", "    if (!l) return;", "browser"],
  ['src', "const fixed = (l, x, y) => x < 0 || y < 0 || x >= l.w || y >= l.h || /^(wall|receiver:|spring:)/.test(l.cells[y * l.w + x]);", "const fixed = (l, x, y) => x < 0 || y < 0 || x >= l.w || y >= l.h || /^(wall)/.test(l.cells[y * l.w + x]);", "lint"],
  ['src', "    if (kind === 'door' || kind === 'idoor') (doors[col] ||= []).push(i);", "    if (kind === 'door') (doors[col] ||= []).push(i);", "lint"],
  ['src', "    if (kind === 'button' || kind === 'receiver' || kind === 'sensor') (switches[col] ||= []).push(i);", "    if (kind === 'button' || kind === 'receiver') (switches[col] ||= []).push(i);", "lint"],
  ['src', "    if (e.kind !== 'turret' && Object.values(DIRS)", "    if (Object.values(DIRS)", "lint"],
  ['src', "    if (s.deaths !== deaths) return n + 1;\n", "", "lint"],
  ['src', "  return s.won ? 0 : moves.length;", "  return 0;", "lint"],
  ['src', "    if (n) warns.unshift(", "    if (false) warns.unshift(", "browser"],
  ['src', "  $('lintBox').hidden = !warns.length;", "  $('lintBox').hidden = true;", "browser"],
  ['src', "    b.onclick = () => S.fx.push({ type: 'flash', x: w.x, y: w.y, at: now() });", "    b.onclick = () => {};", "browser"],
  ['src', "  S.room = { id: meta.id || null, name: meta.name || '', note: meta.note || '', solution: meta.solution || null,", "  S.room = { id: meta.id || null, name: meta.name || '', note: meta.note || '', solution: null,", "browser"],
  ['src', "  for (let i = 1; i <= limit(t) && !settled(t); i++) step(t, i === at ? [then] : []);", "  for (let i = 1; i <= limit(t) && !settled(t); i++) step(t);", "solve"],
  ['src', "      if (pw.dive) out.push(`${d}@${i}:${pd}`);\n", "", "solve"],
  ['src', "      for (const pair of successors(s, keys)) {", "      for (const pair of successors(s, keys, false)) {", "solve"],
  ['src', "  if (w) { if (++w.i === w.at) { S.pending.push(w.then); S.demoWait = null; } return; }", "  if (w) { S.demoWait = null; return; }", "browser"],
  ['src', "  if (then) S.demoWait = { i: 0, at, then };\n", "", "browser"],
  ['src', "    for (let i = 1; i <= 4 * s.w * s.h + 40 && busy(); i++) { step(s, i === at ? [then] : []); watch(); }", "    for (let i = 1; i <= 4 * s.w * s.h + 40 && busy(); i++) { step(s); watch(); }", "tags"],
  ['src', "    if (e.turret && e.kind !== 'turret') tags.add('piece:mounted');\n", "", "tags"],
  ['src', "  if (Object.values(colours).some(n => n > 1)) tags.add('wiring:and');\n", "", "tags"],
  ['src', "  if (Object.keys(colours).length > 1) tags.add('wiring:colours');\n", "", "tags"],
  ['src', "  for (const p of ['boomerang', 'dive', 'laser', 'cycle', 'swim', 'armored']) if (level.powers[p]) tags.add('power:' + p);", "  for (const p of ['boomerang', 'dive', 'laser', 'cycle', 'swim', 'armored']) tags.add('power:' + p);", "tags"],
  ['src', "    if (p.pushing) tags.add('use:push');\n", "", "tags"],
  ['src', "      if (s.cells.includes('door:' + col)) tags.add('use:door-opens');\n", "", "tags"],
  ['src', "    step(s, [k]); watch();\n    for (let i = 1; i <= 4 * s.w * s.h + 40 && busy(); i++) { step(s, i === at ? [then] : []); watch(); }", "    step(s, [k]);\n    for (let i = 1; i <= 4 * s.w * s.h + 40 && busy(); i++) { step(s, i === at ? [then] : []); watch(); }", "tags"],
  ['src', "const solution = r && r.status === 'solved' ? r.moves : null;", "const solution = null;", "browser"],
  ['src', "tagCache.set(v, new Set([...contains(level), ...(r.uses || []), ...(r.recipe ? [GENERATED] : [])])); }", "tagCache.set(v, new Set([...(r.uses || []), ...(r.recipe ? [GENERATED] : [])])); }", "browser"],
  ["src", "      if (filter && !tags.has(filter)) continue;\n", "", "browser"],
  ['src', "  $('unexplored').replaceChildren(...MECHANISMS.filter(([t]) => !counts[t])", "  $('unexplored').replaceChildren(...MECHANISMS.filter(([t]) => counts[t])", "browser"],
  ['src', "  ...(meta.solution ? { par: meta.solution.length, solution: meta.solution, uses: meta.uses || [] } : {}),\n", "", "browser"],
  ["src", "  if (t.deaths !== deaths || !settled(t)) return null;", "  if (!settled(t)) return null;", "solve"],
  ["src", "  if (!t.won && stateKey(t) === before) return null;\n", "", "solve"],
  ["src", "  if (!level.cells.includes('goal')) return 'nogoal';\n", "", "solve"],
  ["src", "|| (e.turret && e.turret.mode === 'realtime'))) return 'realtime';", "|| false)) return 'realtime';", "solve"],
  ["src", "(MOVES.includes(e.kind) && e.mode === 'realtime') || ", "", "solve"],
  ["src", "        if (seen.has(key)) continue;\n", "", "solve"],
  ["src", "        if (seen.size >= max) return { status: 'capped', moves: null, states: seen.size };\n", "", "solve"],
  ["src", "        if (t.won) return { status: 'solved', moves: [...path, k], states: seen.size };", "        if (t.won) return { status: 'solved', moves: [k], states: seen.size };", "solve"],
  ["src", "  return JSON.stringify([p.x, p.y, p.swimming", "  return JSON.stringify([p.y, p.swimming", "solve"],
  ["src", "  if (busy) return;\n", "", "browser"],
  ["src", "  if (!S.check || S.check.stamp === JSON.stringify(S.level)) return;", "  if (!S.check) return;", "browser"],
  ["src", "  $('showSolution').hidden = r.status !== 'solved';", "  $('showSolution').hidden = true;", "browser"],
  ["src", "  if (!name) { say('Give the room a name first.'); $('roomName').focus(); return false; }\n", "", "browser"],
  ["src", "export const dirty = () => !S.room || stampOf(S.level) !== S.room.saved || S.room.edited;", "export const dirty = () => !S.room || S.room.edited;", "browser"],
  ["src", "  if (r) { const { meta, level } = splitRoom(r); openRoom(level, meta); }", "  if (false) { const { meta, level } = splitRoom(r); openRoom(level, meta); }", "browser"],
  ["src", "    for (const r of rooms) await put({ ...r, id: r.id || newId() });", "    for (const r of rooms.slice(1)) await put({ ...r, id: r.id || newId() });", "browser"],
  ["src", "  else { S.room = { id: null, name: '', note: '', saved: stampOf(S.level), edited: false }; syncRoomsButton(); }", "  else { S.room = { id: null, name: '', note: '', saved: null, edited: false }; syncRoomsButton(); }", "single"],
  ["src", "    if (r.ok && (r.headers.get('content-type') || '').includes('json')) { mode = 'server'; return mode; }", "    if (false) { mode = 'server'; return mode; }", "browser"],
  ["tools/api.mjs", "        splitRoom(room);\n", "", "server"],
  ["tools/api.mjs", "const ID = /^[a-z0-9][a-z0-9-]{0,40}$/;", "const ID = /^.+$/;", "server"],
  ["tools/api.mjs", "    req.on('data', c => { size += c.length; if (size > MAX_BYTES) { fail(new Error('too large')); req.destroy(); } else parts.push(c); });", "    req.on('data', c => { parts.push(c); });", "server"],
  ["tools/api.mjs", "  await git(dir, ['add', '-A']);\n", "", "server"],
  ["tools/server.mjs", "    if (!authed(req)) {", "    if (false) {", "server"],
  ["tools/server.mjs", "  if (!password) throw new Error('Set WEE_PASSWORD.');\n", "", "server"],
  ["tools/api.mjs", "        if (!existsSync(file)) { send(res, 404, 'No such room.'); return true; }\n", "", "server"],
  ["tools/server.mjs", "return got.length === want.length && timingSafeEqual(got, want);", "return got.length > 0;", "server"],
  ['src', "  if (before === JSON.stringify(level)) return false;\n", "", "sim"],
  ['src', "  if (h.past.length > LIMIT) h.past.shift();\n", "", "sim"],
  ['src', "  h.past.push(before);\n  if (h.past.length > LIMIT) h.past.shift();\n  h.future = [];", "  h.past.push(before);\n  if (h.past.length > LIMIT) h.past.shift();", "sim"],
  ['src', "  h.future.push(JSON.stringify(level));\n  return JSON.parse(h.past.pop());", "  return JSON.parse(h.past.pop());", "sim"],
  ['src', "  h.past.push(JSON.stringify(level));\n  return JSON.parse(h.future.pop());", "  return JSON.parse(h.future.pop());", "sim"],
  ['src', "    begin();\n    S.painting", "    S.painting", "browser"],
  ['src', "const lift = () => { S.painting = 0; S.swipe = null; end(); };", "const lift = () => { S.painting = 0; S.swipe = null; };", "browser"],
  ['src', "undoStep(ev.key === 'z' && !ev.shiftKey,", "undoStep(true,", "browser"],
  ['src', "  $('undo').disabled = S.mode !== 'edit' || !S.history.past.length;", "  $('undo').disabled = !S.history.past.length;", "browser"],
  ['src', "S.level = parseLevel(JSON.stringify(l)); S.history = newHistory();", "S.level = parseLevel(JSON.stringify(l));", "browser"],
  ['src', "if (s.won || p.dir || p.hidden || cellAt(s, p.x, p.y) !== 'goal') return;", "if (s.won || p.hidden || cellAt(s, p.x, p.y) !== 'goal') return;", "sim"],
  ['src', "if (s.won || p.dir || p.hidden || cellAt(s, p.x, p.y) !== 'goal') return;", "if (s.won || p.dir || cellAt(s, p.x, p.y) !== 'goal') return;", "sim"],
  ['src', "  if (!s.won) for (const k of inputs) input(s, k);", "  for (const k of inputs) input(s, k);", "sim"],
  ['src', "  checkWin(s);\n", "", "sim"],
  ['src', "if (c === 'death' || c === 'water' || c === 'sticky' || c === 'goal') return true;", "if (c === 'death' || c === 'water' || c === 'sticky') return true;", "sim"],
  ['src', "    else if (kind === 'goal') parts.push('Goal');\n", "", "sim"],
  ['src', "} else if (t === 'water' || t === 'sticky' || t === 'goal') {", "} else if (t === 'water' || t === 'sticky') {", "sim"],
  ['src', "    if (e.type === 'win') { $('winText')", "    if (false) { $('winText')", "browser"],
  ['src', "  $('again').onclick = () => setMode('play');\n", "", "browser"],
  ['src', "  $('moves').textContent = `Moves ${game.move}`;\n", "", "browser"],
  ['src', "if (c === 'sticky' && e.kind !== 'turret' && !e.glue && !e.sticky) { e.sticky = true;", "if (false) { e.sticky = true;", 'sim'],
  ['src', "if (c === 'sticky' && e.kind !== 'turret' && !e.glue && !e.sticky) { e.sticky = true;", "if (c === 'sticky' && e.kind !== 'turret' && !e.sticky) { e.sticky = true;", 'sim'],
  ['src', "  if (c === 'water') e.sticky = false;\n", "", 'sim'],
  ['src', "if (!e.sticky || o.kind === 'turret' || partnerOf(s, o)) return false;", "if (!e.sticky || partnerOf(s, o)) return false;", 'sim'],
  ['src', "if (!e.sticky || o.kind === 'turret' || partnerOf(s, o)) return false;", "if (!e.sticky || o.kind === 'turret') return false;", 'sim'],
  ['src', "if (!e.sticky || o.kind === 'turret' || partnerOf(s, o)) return false;", "if (o.kind === 'turret' || partnerOf(s, o)) return false;", 'sim'],
  ['src', "  e.sticky = false;\n  e.glue = o.id;", "  e.glue = o.id;", 'sim'],
  ['src', "e.glue = o.id; o.glue = e.id;", "e.glue = o.id;", 'sim'],
  ['src', "  o.glue = null;\n  s.events.push({ type: 'unglue'", "  s.events.push({ type: 'unglue'", 'sim'],
  ['src', "if (t && !playerAt(s, t.x, t.y)) { land(s, o, t); return true; }", "if (t) { land(s, o, t); return true; }", 'sim'],
  ['src', "if (t && !playerAt(s, t.x, t.y)) { land(s, o, t); return true; }", "if (false) { land(s, o, t); return true; }", 'sim'],
  ['src', "if (!o || Math.abs(o.x - e.x) + Math.abs(o.y - e.y) !== 1) unglue(s, e);", "if (!o) unglue(s, e);", 'sim'],
  ['src', "  checkGlue(s);\n", "", 'sim'],
  ['src', "if (e.rush || e.lastMove === s.move || partnerOf(s, e)?.rush) return;", "if (e.rush || e.lastMove === s.move) return;", 'sim'],
  ['src', "MOVES.includes(e.kind) && !partnerOf(s, e)?.rush) e.rush = true;", "MOVES.includes(e.kind)) e.rush = true;", 'sim'],
  ['src', "  if (ahead && !lead(s, e, mx, my)) { blocked(); return; }\n", "", 'sim'],
  ['src', "  if (ahead && !lead(s, e, mx, my)) { e.slide = null; return; }\n", "", 'sim'],
  ['src', "if (land(s, o, b)) follow(s, o, mx, my); }", "land(s, o, b); }", 'sim'],
  ['src', "    else { meet(s, e, o); blocked(); return; }", "    else { blocked(); return; }", 'sim'],
  ['src', "  land(s, e, t);\n  if (!ahead) follow(s, e, mx, my);\n  if (ridden", "  land(s, e, t);\n  if (ridden", 'sim'],
  ['src', "    if (meet(s, e, o)) { e.slide = null; return; }\n", "", 'sim'],
  ['src', "  land(s, e, t); e.slide = t.d;\n  if (!ahead) follow(s, e, mx, my);\n", "  land(s, e, t); e.slide = t.d;\n", 'sim'],
  ['src', "      const led = !!partnerAt(s, e, nx + dx, ny + dy) && lead(s, e, dx, dy);", "      const led = false;", 'sim'],
  ['src', "{ const o = entAt(s, nx + dx, ny + dy, e); if (o) meet(s, e, o); return 'blocked'; }", "return 'blocked';", 'sim'],
  ['src', "pushed = { id: e.id, d: b.d }; if (!led) follow(s, e, dx, dy); }", "pushed = { id: e.id, d: b.d }; }", 'sim'],
  ['src', "...(partnerOf(s, e) ? { glued: true } : {})", "...{}", 'sim'],
  ['src', "...(e.sticky ? { sticky: true } : {}),", "", 'sim'],
  ['src', "  if (c.startsWith('idoor:')) return !!s.open[c.slice(6)];\n", "", 'sim'],
  ['src', "if (c.startsWith('idoor:')) return !!s.open[c.slice(6)];", "if (c.startsWith('idoor:')) return !s.open[c.slice(6)];", 'sim'],
  ['src', "if (want !== !!s.open[col]) {", "if (!want && s.open[col]) {", 'sim'],
  ['src', "const closing = (want ? 'idoor:' : 'door:') + col, doors = [];", "const closing = 'door:' + col, doors = [];", 'sim'],
  ['src', "(kind === 'button' || kind === 'door' || kind === 'idoor')", "(kind === 'button' || kind === 'door')", 'sim'],
  ['src', "const isDoor = c => c.startsWith('door:') || c.startsWith('idoor:');", "const isDoor = c => c.startsWith('door:');", 'sim'],
  ['src', "const solid = t === 'door' || t === 'idoor' || t === 'receiver';", "const solid = t === 'door' || t === 'receiver';", 'sim'],
  ['src', "    else if (kind === 'idoor') parts.push(`${COLOUR_NAME[v]} inverted door`);\n", "", 'sim'],
  ['src', "tool === 'receiver' || tool === 'sensor' || tool === 'gate') return", "tool === 'receiver' || tool === 'gate') return", 'browser'],
  ['src', "drawPlayer(g, px, py, p.hidden, scale, 1, s.powers.armored, swim, p.sticky);\n  g.restore();", "g.restore();", 'browser'],
  // generator
  ['src', "let a = seed >>> 0;", "let a = 0;", 'gen'],
  ['src', "if (inside(l, i) && l.cells[i] === '' && !taken(l, i)) free.push(i);", "if (inside(l, i) && l.cells[i] === '') free.push(i);", 'gen'],
  ['src', "for (let k = 0; k < n; k++) if (ctx.and || !switchOf(l, col)) tile(l, r, 'button:' + col);", "for (let k = 0; k < n; k++) tile(l, r, 'button:' + col);", 'gen'],
  ['src', "|| r.pick(COLOURS) : 'red';", "|| r.pick(COLOURS) : r.pick(COLOURS);", 'gen'],
  ['src', "return Object.keys(ING).filter(id => !recipe.ing[id] && ING[id].tags.some(t => have.has(t)));", "return Object.keys(ING).filter(id => ING[id].tags.some(t => have.has(t)));", 'gen'],
  ['src', "  if (off.length) return { fit: false, score: -Infinity, status: 'off', off };\n", "", 'gen'],
  ['src', "const out = par < recipe.min ? recipe.min - par : par > recipe.max ? par - recipe.max : 0;", "const out = 0;", 'gen'],
  ['src', "if (!ing[w]) { ing[w] = 'allowed'; grew = true; }", "if (!ing[w]) { grew = false; }", 'gen'],
  ['src', "w: clamp(recipe.w ?? 8, LIMITS.size)", "w: +recipe.w || 8", 'gen'],
  ['src', "if (recipe.ing[g.id] === 'must' || r.next() < 0.5) g.place(l, r, ctx);", "if (r.next() < 0.5) g.place(l, r, ctx);", 'gen'],
  ['src', "  for (const p of Object.keys(l.powers)) l.powers[p] = false;\n", "", 'gen'],
  ['src', "      if (nv.fit) return { fit: true, level: next, verdict: nv, tries: out.tries };\n", "", 'gen'],
  ['src', "if (x > 0 && y > 0 && x < l.w - 1 && y < l.h - 1) inner.push(i);", "inner.push(i);", 'gen'],
  ['src', "const must = INGREDIENTS.filter(g => recipe.ing[g.id] === 'must').map(g => g.label);", "const must = INGREDIENTS.filter(g => recipe.ing[g.id]).map(g => g.label);", 'gen'],
  ['src', "r.moves.length !== par)) continue;", "r.moves.length < par)) continue;", 'gen'],
  ['src', "r.moves.length !== par)) continue;", "r.moves.length > par)) continue;", 'gen'],
  ['src', "if (r.status === 'unsolvable' || (r.status === 'solved'", "if ((r.status === 'solved'", 'gen'],
  ['src', "const noButtons = l => ({ ...l, cells: l.cells.map(c => c.startsWith('button:') ? '' : c) });", "const noButtons = l => l;", 'gen'],
  ['src', "g.power ? { ...l, powers: { ...l.powers, [g.power]: false } } :", "g.power ? l :", 'gen'],
  ['src', "e.mode === 'follow' ? { ...e, mode: 'input' } : e", "e", 'gen'],
  ['src', "e.turret && e.kind !== 'turret' ? { ...e, turret: undefined } : e", "e", 'gen'],
  ['src', "c.startsWith('receiver:') ? 'wall' : c", "c", 'gen'],
  ['src', "ing[id] = ING[id].allowedOnly ? 'allowed' : v;", "ing[id] = v;", 'gen'],
  ['src', "tags: ['tile:door'], with: ['box'],", "tags: ['tile:door'],", 'gen'],
  ['src', "sel.append(...CHOICES.filter(([v]) => !(g.allowedOnly && v === 'must'))", "sel.append(...CHOICES.filter(() => true)", 'genui'],
  ['src', "    if (inBeam(s)) { die(s); break; }\n", "", 'sim'],
  ['src', "  placeOptions(wide);\n", "", 'fit'],
  ['style.css', "  main > * { min-height: 0; overflow-y: auto; scrollbar-width: thin; }", "  main > * { min-height: 0; overflow-y: visible; }", 'fit'],
  ['src', "if (n.dist + 1 === par) count += w; }", "if (n.dist + 1 === par) count = 1; }", 'design'],
  ['src', "    if (!level.powers[p] || NEEDS[p]) continue;", "    if (NEEDS[p]) continue;", 'design'],
  ['src', "    if (!c || c === 'wall' || c === 'goal') continue;", "    if (!c) continue;", 'design'],
  ['src', "if (!alive.has(k)) { alive.add(k); todo.push(k); }", "if (!alive.has(k)) alive.add(k);", 'designui'],
  ['src', "if (nodes.size >= max) return null;", "", 'design'],
  ['src', "const idle = ps.filter(p => p.without === par);", "const idle = [];", 'designui'],
  ['src', "  S.check = null;\n  clearDesign();", "  S.check = null;", 'designui'],
  ['src', "liveTimer = setTimeout(() => { if (!S.check && JSON.stringify(S.level) === stamp) runCheck(true); }, LIVE_WAIT_MS);", "", 'designui'],
  ['src', "if (r.status === 'solved' && !S.check.live) runDesign", "if (r.status === 'solved') runDesign", 'designui'],
  ['src', "const unused = es.filter(e => e.without === par), plain", "const unused = [], plain", 'designui'],
  ['src', "plain = es.filter(e => e.without !== par && e.standIn === par);", "plain = [];", 'designui'],
  ['src', ": { ...level, cells: walled(e.y * level.w + e.x), entities: rest };", ": null;", 'design'],
  ['src', "const stand = held.has(i) || c.startsWith('receiver:') ? null", "const stand = c.startsWith('receiver:') ? null", 'design'],
  ['src', "export const variants = (g, l) => [knock(g, l), standIn(g, l)].filter(Boolean);", "export const variants = (g, l) => [knock(g, l)];", 'gen'],
  ['src', "wide ? roomHeight() :", "wide ? innerHeight - canvas.getBoundingClientRect().top - 170 :", 'fit'],
  ['src', "const ro = new ResizeObserver(() => requestAnimationFrame(fit));", "const ro = { observe() {} };", 'fit'],
  ['src', "if (canvas.width !== cw || canvas.height !== ch) { canvas.width = cw; canvas.height = ch; }", "canvas.width = cw; canvas.height = ch;", 'designui'],
  ['src', "e.turret ? e.turret.aim % e.turret.dirs.length : -1", "e.turret ? e.turret.aim : -1", 'solve'],
  ['src', "    if (!confirm('This room has changes. Open the generated room instead?')) return false;\n", "", 'genui'],
  ['src', "    if (!confirm(`Replace ${name}? Its unsaved changes go. Undo brings them back.`)) return false;\n", "", 'genui'],
  ['src', "change(() => { S.level = structuredClone(entry.level); });", "S.level = structuredClone(entry.level);", 'genui'],
  ['src', "if (S.room === g.gen && now === g.prevStamp) S.room = g.prev;", "if (false) S.room = g.prev;", 'genui'],
  ['src', "else if (S.room === g.prev && now === g.genStamp) S.room = g.gen;", "else if (false) S.room = g.gen;", 'genui'],
  ['src', "if (performance.now() > until || $('genStop')", "if ($('genStop')", 'genui'],
  ['src', "$('genStop').dataset.stop === String(my)) {", "false) {", 'genui'],
  ['src', "solution, uses: solution ? uses(S.level, solution) : [], recipe: S.room.recipe }", "solution, uses: solution ? uses(S.level, solution) : [] }", 'genui'],
  ['src', "...(r.recipe ? [GENERATED] : [])", "...[]", 'genui'],
  ['src', "sel.onchange = () => fillForm(recipeFromForm());", "sel.onchange = () => {};", 'genui'],
  ['src', "write(SHELF, [entry, ...shelf()].slice(0, KEEP));", "write(SHELF, [entry]);", 'genui'],
  ['src', "KEEP = 20, SLICE_MS = 25;", "KEEP = 20, SLICE_MS = 3000;", 'perf'],
];

let caught = 0, crashed = 0;
// 'src' as the file means: whichever source file holds the text, which must be exactly one.
const walk = d => readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(d + '/' + e.name) : /\.js$/.test(e.name) ? [d + '/' + e.name] : []);
const locate = (file, from) => {
  if (file !== 'src') return readFileSync(file, 'utf8').includes(from) ? file : null;
  const hits = walk('src').filter(f => readFileSync(f, 'utf8').includes(from));
  return hits.length === 1 ? hits[0] : null;
};
for (const [where, from, to, test] of M) {
  if (process.env.ONLY && !from.includes(process.env.ONLY)) { caught++; continue; }
  const file = locate(where, from);
  if (!file) { console.log(`STALE mutant in ${where}: ${from.slice(0, 50)}`); process.exitCode = 1; continue; }
  if (process.env.STALE_ONLY) { caught++; continue; }
  const orig = readFileSync(file, 'utf8');
  writeFileSync(file, orig.replace(from, to));
  try {
    const r = spawnSync('node', [`tests/${test}.${['sim', 'arch', 'solve', 'server', 'tags', 'lint', 'code', 'region', 'gen', 'design'].includes(test) ? 'test' : 'smoke'}.mjs`], { encoding: 'utf8' });
    const out = r.stdout + r.stderr;
    const fail = out.split('\n').find(l => l.startsWith('FAIL'));
    if (fail) { caught++; console.log(`caught  ${fail.slice(0, 90)}`); }
    else if (r.status !== 0) { crashed++; console.log(`CRASHED ${file}: ${from.slice(0, 50)}`); }
    else console.log(`SURVIVED ${file}: ${from.slice(0, 60)}`);
  } finally { writeFileSync(file, orig); }
}
console.log(`mutants: ${caught}/${M.length} caught${crashed ? `, ${crashed} crashed` : ''}`);
process.exit(caught === M.length ? 0 : 1);
